[workspace]
resolver = "2"
members = [
    "crates/vim-buffer",
    "crates/vim-formatter",
    "crates/vim-input",
    "crates/vim-regex",
    "crates/vim-script", "crates/vim-ui",
]
exclude = ["crates/zed"]

[package]
name = "nxvim"
version = "0.1.0"
edition = "2024"
license = "Vim"
publish = false

[profile.dev]
debug = 1

[dependencies]
crossterm = "0.29"
proptest = { version = "1.9", optional = true }
vim-buffer = { path = "crates/vim-buffer" }
vim-formatter = { path = "crates/vim-formatter" }
vim-regex = { path = "crates/vim-regex" }
vim-script = { path = "crates/vim-script" }
vim-ui = { path = "crates/vim-ui" }
vim-input = { path = "crates/vim-input" }
