[workspace]
resolver = "2"
members = [
    # "crates/vim-buffer",
    "crates/vim-formatter",
    "crates/vim-input",
    "crates/vim-regex",
    "crates/vim-script",
    # "crates/vim-ui",
]
exclude = ["crates/zed"]

[package]
name = "nxvim"
version = "0.1.0"
edition = "2024"
license = "Vim"
publish = false

[profile.dev]
debug = 1

[dependencies]
clock = { path = "crates/zed/crates/clock" }
collections = { path = "crates/zed/crates/collections" }
color-eyre = "0.6.5"
crossterm = "0.29"

libloading = "0.9.0"
log = "0.4"

onig = { version = "6.5.2", default-features = false }
proptest = { version = "1.9", optional = true }
rand = "0.8.5"
rope = { path = "crates/zed/crates/rope" }
serde = { version = "1.0.217", features = ["derive"] }

smallvec = "1.13"
smol = "2.0.2"
sum_tree = { path = "crates/zed/crates/sum_tree" }
syntect = { git = "https://github.com/trishume/syntect" }
text = { path = "crates/zed/crates/text" }

toml = "0.8.19"
tree-sitter = "0.26"
tree-sitter-asm = "0.24.0"
tree-sitter-bash = "0.25.1"
tree-sitter-c = "0.24.1"
tree-sitter-rust = "0.24"
tree-sitter-zig = "1.1.2"

unicode-segmentation = "1.12.0"
util = { path = "crates/zed/crates/util" }
# vim-buffer = { path = "crates/vim-buffer" }
vim-formatter = { path = "crates/vim-formatter" }
vim-input = { path = "crates/vim-input" }
vim-regex = { path = "crates/vim-regex" }
vim-script = { path = "crates/vim-script" }
vim-ui = { path = "crates/vim-ui" }
