use vim_script::host::{
    AddressInterpretation, BarBehavior, Capability, CommandDefinition, FilenameBehavior,
};

pub struct CommandSpec {
    pub name: &'static str,
    pub minimum_abbreviation: usize,
    pub aliases: &'static [(&'static str, usize)],
    pub accepts_bang: bool,
    pub accepts_range: bool,
    pub accepts_count: bool,
    pub accepts_register: bool,
    pub accepts_opt: bool,
    pub accepts_cmd: bool,
    pub filename_behavior: FilenameBehavior,
    pub bar_behavior: BarBehavior,
    pub allowed_modifiers: &'static [&'static str],
    pub required_capabilities: &'static [Capability],
    pub default_range: Option<&'static str>,
    pub address_interpretation: AddressInterpretation,
    pub handler_id: &'static str,
    pub vim_error_behavior: &'static str,
    pub is_extension: bool,
}

impl From<&CommandSpec> for CommandDefinition {
    fn from(spec: &CommandSpec) -> Self {
        Self {
            name: spec.name.to_owned(),
            minimum_abbreviation: spec.minimum_abbreviation,
            aliases: spec
                .aliases
                .iter()
                .map(|(a, m)| (a.to_string(), *m))
                .collect(),
            accepts_bang: spec.accepts_bang,
            accepts_range: spec.accepts_range,
            accepts_count: spec.accepts_count,
            accepts_register: spec.accepts_register,
            accepts_opt: spec.accepts_opt,
            accepts_cmd: spec.accepts_cmd,
            filename_behavior: spec.filename_behavior,
            bar_behavior: spec.bar_behavior,
            allowed_modifiers: spec
                .allowed_modifiers
                .iter()
                .map(|s| s.to_string())
                .collect(),
            required_capabilities: spec.required_capabilities.to_vec(),
            default_range: spec.default_range.map(|s| s.to_owned()),
            address_interpretation: spec.address_interpretation,
            handler_id: spec.handler_id.to_owned(),
            vim_error_behavior: spec.vim_error_behavior.to_owned(),
            is_extension: spec.is_extension,
        }
    }
}

macro_rules! simple_command {
    ($name:literal, $minimum:literal, $aliases:expr, $bang:literal, $range:literal, $filename:expr, $bars:expr, $address:expr) => {
        CommandSpec {
            name: $name,
            minimum_abbreviation: $minimum,
            aliases: $aliases,
            accepts_bang: $bang,
            accepts_range: $range,
            accepts_count: false,
            accepts_register: false,
            accepts_opt: false,
            accepts_cmd: false,
            filename_behavior: $filename,
            bar_behavior: $bars,
            allowed_modifiers: &["silent", "verbose"],
            required_capabilities: &[Capability::Editor],
            default_range: None,
            address_interpretation: $address,
            handler_id: $name,
            vim_error_behavior: "E194",
            is_extension: false,
        }
    };
}

pub static COMMAND_SPECS: &[CommandSpec] = &[
    CommandSpec {
        name: "quit",
        minimum_abbreviation: 1,
        aliases: &[("q", 1)],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "quit",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "write",
        minimum_abbreviation: 1,
        aliases: &[("w", 1)],
        accepts_bang: true,
        accepts_range: true,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: true,
        accepts_cmd: true,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose", "keepalt"],
        required_capabilities: &[Capability::Editor],
        default_range: Some("%"),
        address_interpretation: AddressInterpretation::Lines,
        handler_id: "write",
        vim_error_behavior: "E86",
        is_extension: false,
    },
    CommandSpec {
        name: "bnext",
        minimum_abbreviation: 2,
        aliases: &[("bn", 2)],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: true,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "bnext",
        vim_error_behavior: "E85",
        is_extension: false,
    },
    CommandSpec {
        name: "bprevious",
        minimum_abbreviation: 3,
        aliases: &[("bp", 2), ("bNext", 2), ("bN", 2)],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: true,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "bprevious",
        vim_error_behavior: "E85",
        is_extension: false,
    },
    CommandSpec {
        name: "save",
        minimum_abbreviation: 4,
        aliases: &[],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Required,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "save",
        vim_error_behavior: "E194",
        is_extension: true,
    },
    CommandSpec {
        name: "tabnext",
        minimum_abbreviation: 4,
        aliases: &[("tabn", 4), ("nexttab", 7)],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: true,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &[],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "tabnext",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "tabprevious",
        minimum_abbreviation: 5,
        aliases: &[("tabp", 4), ("previoustab", 11)],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: true,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &[],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "tabprevious",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "tabnew",
        minimum_abbreviation: 6,
        aliases: &[],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "tabnew",
        vim_error_behavior: "E172",
        is_extension: false,
    },
    CommandSpec {
        name: "tabclose",
        minimum_abbreviation: 4,
        aliases: &[("tabc", 4)],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "tabclose",
        vim_error_behavior: "E784",
        is_extension: false,
    },
    CommandSpec {
        name: "edit",
        minimum_abbreviation: 1,
        aliases: &[("e", 1)],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: true,
        accepts_cmd: true,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "edit",
        vim_error_behavior: "E172",
        is_extension: false,
    },
    CommandSpec {
        name: "split",
        minimum_abbreviation: 2,
        aliases: &[("sp", 2), ("hsplit", 2), ("hs", 2)],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: true,
        accepts_cmd: true,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "split",
        vim_error_behavior: "E172",
        is_extension: false,
    },
    CommandSpec {
        name: "vsplit",
        minimum_abbreviation: 3,
        aliases: &[("vs", 2)],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: true,
        accepts_cmd: true,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "vsplit",
        vim_error_behavior: "E172",
        is_extension: false,
    },
    CommandSpec {
        name: "new",
        minimum_abbreviation: 3,
        aliases: &[],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "new",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "vnew",
        minimum_abbreviation: 3,
        aliases: &[],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "vnew",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "enew",
        minimum_abbreviation: 4,
        aliases: &[],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "enew",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "view",
        minimum_abbreviation: 4,
        aliases: &[],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: true,
        accepts_cmd: true,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "edit",
        vim_error_behavior: "E172",
        is_extension: false,
    },
    CommandSpec {
        name: "visual",
        minimum_abbreviation: 2,
        aliases: &[("vi", 2)],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: true,
        accepts_cmd: true,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "edit",
        vim_error_behavior: "E172",
        is_extension: false,
    },
    CommandSpec {
        name: "ex",
        minimum_abbreviation: 2,
        aliases: &[],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: true,
        accepts_cmd: true,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "edit",
        vim_error_behavior: "E172",
        is_extension: false,
    },
    CommandSpec {
        name: "update",
        minimum_abbreviation: 2,
        aliases: &[("up", 2)],
        accepts_bang: true,
        accepts_range: true,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: true,
        accepts_cmd: true,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: Some("%"),
        address_interpretation: AddressInterpretation::Lines,
        handler_id: "write",
        vim_error_behavior: "E86",
        is_extension: false,
    },
    CommandSpec {
        name: "saveas",
        minimum_abbreviation: 3,
        aliases: &[("sav", 3)],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: true,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Required,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "saveas",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "qall",
        minimum_abbreviation: 2,
        aliases: &[("qa", 2)],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "qall",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "quitall",
        minimum_abbreviation: 5,
        aliases: &[("quita", 5)],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "qall",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "cquit",
        minimum_abbreviation: 2,
        aliases: &[("cq", 2)],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "cquit",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "wq",
        minimum_abbreviation: 2,
        aliases: &[],
        accepts_bang: true,
        accepts_range: true,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: true,
        accepts_cmd: true,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose", "keepalt"],
        required_capabilities: &[Capability::Editor],
        default_range: Some("%"),
        address_interpretation: AddressInterpretation::Lines,
        handler_id: "wq",
        vim_error_behavior: "E86",
        is_extension: false,
    },
    CommandSpec {
        name: "xit",
        minimum_abbreviation: 1,
        aliases: &[("x", 1)],
        accepts_bang: true,
        accepts_range: true,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: true,
        accepts_cmd: true,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose", "keepalt"],
        required_capabilities: &[Capability::Editor],
        default_range: Some("%"),
        address_interpretation: AddressInterpretation::Lines,
        handler_id: "wq",
        vim_error_behavior: "E86",
        is_extension: false,
    },
    CommandSpec {
        name: "exit",
        minimum_abbreviation: 4,
        aliases: &[("exi", 3)],
        accepts_bang: true,
        accepts_range: true,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: true,
        accepts_cmd: true,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose", "keepalt"],
        required_capabilities: &[Capability::Editor],
        default_range: Some("%"),
        address_interpretation: AddressInterpretation::Lines,
        handler_id: "wq",
        vim_error_behavior: "E86",
        is_extension: false,
    },
    CommandSpec {
        name: "wqall",
        minimum_abbreviation: 3,
        aliases: &[("wqa", 3), ("xa", 2), ("xall", 4)],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "wqall",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "read",
        minimum_abbreviation: 1,
        aliases: &[("r", 1)],
        accepts_bang: false,
        accepts_range: true,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: true,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: Some("."),
        address_interpretation: AddressInterpretation::Lines,
        handler_id: "read",
        vim_error_behavior: "E484",
        is_extension: false,
    },
    CommandSpec {
        name: "file",
        minimum_abbreviation: 1,
        aliases: &[("f", 1)],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "file",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "pwd",
        minimum_abbreviation: 3,
        aliases: &[],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &[],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "pwd",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "cd",
        minimum_abbreviation: 2,
        aliases: &[],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &[],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "cd",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "chdir",
        minimum_abbreviation: 3,
        aliases: &[],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &[],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "cd",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "lcd",
        minimum_abbreviation: 3,
        aliases: &[],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &[],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "cd",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "tcd",
        minimum_abbreviation: 3,
        aliases: &[],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &[],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "cd",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "checktime",
        minimum_abbreviation: 5,
        aliases: &[],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &[],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "checktime",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "delete",
        minimum_abbreviation: 1,
        aliases: &[("d", 1), ("dl", 2), ("dp", 2)],
        accepts_bang: false,
        accepts_range: true,
        accepts_count: true,
        accepts_register: true,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: Some("."),
        address_interpretation: AddressInterpretation::Lines,
        handler_id: "delete",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "yank",
        minimum_abbreviation: 1,
        aliases: &[("y", 1)],
        accepts_bang: false,
        accepts_range: true,
        accepts_count: true,
        accepts_register: true,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: Some("."),
        address_interpretation: AddressInterpretation::Lines,
        handler_id: "yank",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "put",
        minimum_abbreviation: 2,
        aliases: &[("pu", 2), ("iput", 4)],
        accepts_bang: true,
        accepts_range: true,
        accepts_count: false,
        accepts_register: true,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: Some("."),
        address_interpretation: AddressInterpretation::Lines,
        handler_id: "put",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "copy",
        minimum_abbreviation: 2,
        aliases: &[("co", 2), ("t", 1)],
        accepts_bang: false,
        accepts_range: true,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: Some("."),
        address_interpretation: AddressInterpretation::Lines,
        handler_id: "copy",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "move",
        minimum_abbreviation: 1,
        aliases: &[("m", 1)],
        accepts_bang: false,
        accepts_range: true,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: Some("."),
        address_interpretation: AddressInterpretation::Lines,
        handler_id: "move",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "join",
        minimum_abbreviation: 1,
        aliases: &[("j", 1)],
        accepts_bang: true,
        accepts_range: true,
        accepts_count: true,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: Some(".,.+1"),
        address_interpretation: AddressInterpretation::Lines,
        handler_id: "join",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "print",
        minimum_abbreviation: 1,
        aliases: &[
            ("p", 1),
            ("P", 1),
            ("list", 2),
            ("number", 2),
            ("nu", 2),
            ("z", 1),
        ],
        accepts_bang: false,
        accepts_range: true,
        accepts_count: true,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: Some("."),
        address_interpretation: AddressInterpretation::Lines,
        handler_id: "print",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "change",
        minimum_abbreviation: 1,
        aliases: &[("c", 1)],
        accepts_bang: true,
        accepts_range: true,
        accepts_count: true,
        accepts_register: true,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &[],
        required_capabilities: &[Capability::Editor],
        default_range: Some("."),
        address_interpretation: AddressInterpretation::Lines,
        handler_id: "change",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "/",
        minimum_abbreviation: 1,
        aliases: &[],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &[],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "placeholders",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "?",
        minimum_abbreviation: 1,
        aliases: &[],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &[],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "placeholders",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "substitute",
        minimum_abbreviation: 1,
        aliases: &[("s", 1), ("&", 1), ("~", 1), ("smagic", 7), ("snomagic", 9)],
        accepts_bang: false,
        accepts_range: true,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &[],
        required_capabilities: &[Capability::Editor],
        default_range: Some("."),
        address_interpretation: AddressInterpretation::Lines,
        handler_id: "substitute",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "/",
        minimum_abbreviation: 1,
        aliases: &[],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &[],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "/",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "?",
        minimum_abbreviation: 1,
        aliases: &[],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &[],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "?",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "global",
        minimum_abbreviation: 1,
        aliases: &[("g", 1)],
        accepts_bang: true,
        accepts_range: true,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &[],
        required_capabilities: &[Capability::Editor],
        default_range: Some("%"),
        address_interpretation: AddressInterpretation::Lines,
        handler_id: "placeholders",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "vglobal",
        minimum_abbreviation: 1,
        aliases: &[("v", 1)],
        accepts_bang: false,
        accepts_range: true,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &[],
        required_capabilities: &[Capability::Editor],
        default_range: Some("%"),
        address_interpretation: AddressInterpretation::Lines,
        handler_id: "placeholders",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "nohlsearch",
        minimum_abbreviation: 4,
        aliases: &[("nohl", 4)],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &[],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "placeholders",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "vimgrep",
        minimum_abbreviation: 7,
        aliases: &[],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &[],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "placeholders",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "vimgrepadd",
        minimum_abbreviation: 10,
        aliases: &[],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &[],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "placeholders",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "colorscheme",
        minimum_abbreviation: 4,
        aliases: &[],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "colorscheme",
        vim_error_behavior: "E185",
        is_extension: false,
    },
    CommandSpec {
        name: "set",
        minimum_abbreviation: 2,
        aliases: &[("se", 2)],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "set",
        vim_error_behavior: "E518",
        is_extension: false,
    },
    CommandSpec {
        name: "syntax",
        minimum_abbreviation: 3,
        aliases: &[("syn", 3)],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "syntax",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "treesitter",
        minimum_abbreviation: 3,
        aliases: &[("tre", 3)],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "treesitter",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "indexer",
        minimum_abbreviation: 3,
        aliases: &[("ind", 3)],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "indexer",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "inspect",
        minimum_abbreviation: 3,
        aliases: &[("ins", 3)],
        accepts_bang: false,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Optional,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "inspect",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    simple_command!(
        "buffer",
        1,
        &[("b", 1)],
        true,
        false,
        FilenameBehavior::Optional,
        BarBehavior::Chainable,
        AddressInterpretation::Buffers
    ),
    simple_command!(
        "bdelete",
        2,
        &[("bd", 2)],
        true,
        false,
        FilenameBehavior::Optional,
        BarBehavior::Chainable,
        AddressInterpretation::Buffers
    ),
    simple_command!(
        "only",
        2,
        &[("on", 2)],
        true,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::Windows
    ),
    simple_command!(
        "close",
        2,
        &[("cl", 2)],
        true,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::Windows
    ),
    simple_command!(
        "copen",
        2,
        &[],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "cclose",
        2,
        &[],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "lopen",
        2,
        &[],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "lclose",
        2,
        &[],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "cnext",
        2,
        &[("cn", 2)],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "cprevious",
        2,
        &[("cprev", 2), ("cp", 2)],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "cfirst",
        2,
        &[("crewind", 2)],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "clast",
        2,
        &[],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "lnext",
        3,
        &[("lne", 3)],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "lprevious",
        2,
        &[("lprev", 2), ("lp", 2)],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "lfirst",
        2,
        &[("lrewind", 2)],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "llast",
        2,
        &[],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "normal",
        4,
        &[("norm", 4)],
        true,
        true,
        FilenameBehavior::None,
        BarBehavior::Argument,
        AddressInterpretation::Lines
    ),
    simple_command!(
        "sort",
        3,
        &[],
        true,
        true,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::Lines
    ),
    simple_command!(
        "command",
        3,
        &[],
        true,
        false,
        FilenameBehavior::None,
        BarBehavior::Argument,
        AddressInterpretation::None
    ),
    simple_command!(
        "delcommand",
        4,
        &[],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "abbreviate",
        2,
        &[("ab", 2)],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "iabbrev",
        2,
        &[("ia", 2)],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "cabbrev",
        2,
        &[("ca", 2)],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "noreabbrev",
        5,
        &[("norea", 5)],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "inoreabbrev",
        6,
        &[("inorea", 6)],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "cnoreabbrev",
        6,
        &[("cnorea", 6)],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "unabbreviate",
        3,
        &[("una", 3)],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "iunabbrev",
        4,
        &[("iuna", 4)],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "cunabbrev",
        4,
        &[("cuna", 4)],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "abclear",
        3,
        &[("abc", 3)],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "iabclear",
        4,
        &[("iabc", 4)],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    simple_command!(
        "cabclear",
        4,
        &[("cabc", 4)],
        false,
        false,
        FilenameBehavior::None,
        BarBehavior::Chainable,
        AddressInterpretation::None
    ),
    CommandSpec {
        name: "source",
        minimum_abbreviation: 2,
        aliases: &[("so", 2)],
        accepts_bang: true,
        accepts_range: false,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::Required,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::None,
        handler_id: "source",
        vim_error_behavior: "E194",
        is_extension: false,
    },
    CommandSpec {
        name: "",
        minimum_abbreviation: 0,
        aliases: &[],
        accepts_bang: false,
        accepts_range: true,
        accepts_count: false,
        accepts_register: false,
        accepts_opt: false,
        accepts_cmd: false,
        filename_behavior: FilenameBehavior::None,
        bar_behavior: BarBehavior::Chainable,
        allowed_modifiers: &["silent", "verbose"],
        required_capabilities: &[Capability::Editor],
        default_range: None,
        address_interpretation: AddressInterpretation::Lines,
        handler_id: "",
        vim_error_behavior: "E194",
        is_extension: false,
    },
];
