[metadata]
name = "catppuccin-mocha"
description = ""
author = "github/catppuccin"
github = "https://github.com/catppuccin/nvim"
type = "dark"

[colors]
c_0 = "#005523"
c_1 = "#11111b"
c_2 = "#181825"
c_3 = "#1e1e2e"
c_4 = "#25293c"
c_5 = "#283040"
c_6 = "#29313e"
c_7 = "#2a2b3c"
c_8 = "#313244"
c_9 = "#32283a"
c_10 = "#33313a"
c_11 = "#364143"
c_12 = "#393b4d"
c_13 = "#3e4b6b"
c_14 = "#3e5767"
c_15 = "#443244"
c_16 = "#45475a"
c_17 = "#590008"
c_18 = "#6b5300"
c_19 = "#6c7086"
c_20 = "#74c7ec"
c_21 = "#7ec9d8"
c_22 = "#7f849c"
c_23 = "#89b4fa"
c_24 = "#89dceb"
c_25 = "#9399b2"
c_26 = "#94e2d5"
c_27 = "#a6adc8"
c_28 = "#a6e3a1"
c_29 = "#b4befe"
c_30 = "#cba6f7"
c_31 = "#cdd6f4"
c_32 = "#eba0ac"
c_33 = "#f2cdcd"
c_34 = "#f38ba8"
c_35 = "#f5c2e7"
c_36 = "#f5e0dc"
c_37 = "#f9e2af"
c_38 = "#fab387"
c_39 = "#ff0000"
c_40 = "#ffc0b9"

[ui]
background = "c_3"
border_background = "c_3"
border_foreground = "c_1"
caret = "c_3"
cursor_line = "c_7"
cursor_line_nr = "c_29"
diagnostic_error = "c_34"
diagnostic_hint = "c_26"
diagnostic_info = "c_24"
diagnostic_ok = "c_28"
diagnostic_warn = "c_37"
diff_add_background = "c_11"
diff_add_foreground = "c_28"
diff_change_background = "c_4"
diff_change_foreground = "c_23"
diff_delete_background = "c_15"
diff_delete_foreground = "c_40"
diff_text_background = "c_13"
error = "c_34"
find_highlight = "c_21"
find_highlight_foreground = "c_2"
float_background = "c_2"
float_border_background = "c_2"
float_border_foreground = "c_23"
float_foreground = "c_31"
foreground = "c_31"
gutter_foreground = "c_16"
match_paren_background = "c_12"
match_paren_foreground = "c_38"
non_text = "c_19"
pmenu_background = "c_2"
pmenu_foreground = "c_25"
pmenu_sbar = "c_8"
pmenu_sel_background = "c_8"
pmenu_sel_foreground = "c_31"
pmenu_thumb = "c_19"
selection = "c_16"
special_key = "c_19"
statusline_background = "c_2"
statusline_foreground = "c_31"
statusline_nc_background = "c_2"
statusline_nc_foreground = "c_16"
tabline_background = "c_1"
tabline_fill = "c_2"
tabline_foreground = "c_19"
tabline_sel_background = "c_3"
tabline_sel_foreground = "c_31"
warning = "c_37"
whitespace = "c_16"

[syntax]
boolean = "c_38"
character = "c_26"
comment = "c_35"
constant = "c_38"
constructor = "c_37"
delimiter = "c_25"
error = "c_34"
float = "c_38"
function = "c_23"
heading = "c_23"
keyword = "c_35"
link = "c_29"
module = "c_37"
number = "c_38"
operator = "c_24"
property = "c_29"
special = "c_35"
string = "c_28"
tag = "c_23"
tag_attribute = "c_37"
tag_delimiter = "c_26"
todo = "c_3"
type = "c_37"
variable = "c_31"
