[metadata]
name = "kanagawa"
description = ""
author = "github/rebelot"
github = "https://github.com/rebelot/kanagawa.nvim"
type = "dark"

[colors]
c_0 = "#005523"
c_1 = "#16161d"
c_2 = "#181820"
c_3 = "#1a1a22"
c_4 = "#1f1f28"
c_5 = "#223249"
c_6 = "#252535"
c_7 = "#2a2a37"
c_8 = "#2b3328"
c_9 = "#2d4f67"
c_10 = "#363646"
c_11 = "#43242b"
c_12 = "#49443c"
c_13 = "#4f5258"
c_14 = "#54546d"
c_15 = "#590008"
c_16 = "#658594"
c_17 = "#6a9589"
c_18 = "#6b5300"
c_19 = "#717c7c"
c_20 = "#727169"
c_21 = "#76946a"
c_22 = "#7aa89f"
c_23 = "#7e9cd8"
c_24 = "#7fb4ca"
c_25 = "#8cf8f7"
c_26 = "#938aa9"
c_27 = "#957fb8"
c_28 = "#98bb6c"
c_29 = "#9cabca"
c_30 = "#b3f6c0"
c_31 = "#b8b4d0"
c_32 = "#c0a36e"
c_33 = "#c34043"
c_34 = "#c8c093"
c_35 = "#d27e99"
c_36 = "#dca561"
c_37 = "#dcd7ba"
c_38 = "#e46876"
c_39 = "#e6c384"
c_40 = "#e82424"
c_41 = "#ff0000"
c_42 = "#ff5d62"
c_43 = "#ff9e3b"
c_44 = "#ffa066"
c_45 = "#ffc0b9"

[ui]
background = "c_4"
border_background = "c_4"
border_foreground = "c_1"
caret = "c_4"
cursor_line = "c_10"
cursor_line_nr = "c_43"
diagnostic_error = "c_40"
diagnostic_hint = "c_17"
diagnostic_info = "c_16"
diagnostic_ok = "c_28"
diagnostic_warn = "c_43"
diff_add_background = "c_8"
diff_add_foreground = "c_30"
diff_change_background = "c_6"
diff_change_foreground = "c_25"
diff_delete_background = "c_11"
diff_delete_foreground = "c_33"
diff_text_background = "c_12"
error = "c_40"
find_highlight = "c_9"
find_highlight_foreground = "c_37"
float_background = "c_1"
float_border_background = "c_1"
float_border_foreground = "c_14"
float_foreground = "c_34"
foreground = "c_37"
gutter = "c_7"
gutter_foreground = "c_14"
match_paren_background = "c_4"
match_paren_foreground = "c_43"
non_text = "c_14"
pmenu_background = "c_5"
pmenu_foreground = "c_37"
pmenu_sbar = "c_5"
pmenu_sel_background = "c_9"
pmenu_sel_foreground = "c_37"
pmenu_thumb = "c_9"
selection = "c_5"
special_key = "c_26"
statusline_background = "c_1"
statusline_foreground = "c_34"
statusline_nc_background = "c_1"
statusline_nc_foreground = "c_14"
tabline_background = "c_1"
tabline_fill = "c_4"
tabline_foreground = "c_26"
tabline_sel_background = "c_7"
tabline_sel_foreground = "c_34"
warning = "c_43"
whitespace = "c_14"

[syntax]
boolean = "c_44"
character = "c_28"
comment = "c_20"
constant = "c_44"
constructor = "c_24"
delimiter = "c_29"
error = "c_40"
float = "c_35"
function = "c_23"
heading = "c_23"
keyword = "c_27"
link = "c_24"
module = "c_22"
number = "c_35"
operator = "c_32"
property = "c_39"
special = "c_24"
string = "c_28"
tag = "c_24"
tag_attribute = "c_39"
tag_delimiter = "c_29"
todo = "c_5"
type = "c_22"
variable = "c_39"
