#!/usr/bin/env python3
"""Generate Unicode 17 grapheme tables and conformance vectors for the Zig rope.

The input is unicode-segmentation 1.13.3's generated `src/tables.rs` and
`tests/testdata/mod.rs`. The crate records that both are generated from Unicode
17.0.0 data, including GraphemeBreakTest.txt.
"""

from __future__ import annotations

import argparse
import ast
import re
from pathlib import Path

DEFAULT_CRATE = Path(
    "/home/iceman/.cargo/registry/src/"
    "index.crates.io-1949cf8c6b5b557f/unicode-segmentation-1.13.3"
)
PROPERTY_NAMES = {
    "GC_Control": "control",
    "GC_CR": "cr",
    "GC_Extend": "extend",
    "GC_Extended_Pictographic": "extended_pictographic",
    "GC_InCB_Consonant": "incb_consonant",
    "GC_L": "l",
    "GC_LF": "lf",
    "GC_LV": "lv",
    "GC_LVT": "lvt",
    "GC_Prepend": "prepend",
    "GC_Regional_Indicator": "regional_indicator",
    "GC_SpacingMark": "spacing_mark",
    "GC_T": "t",
    "GC_V": "v",
    "GC_ZWJ": "zwj",
}
RUST_RANGE = re.compile(
    r"\(\s*'\\u\{([0-9a-f]+)\}'\s*,\s*'\\u\{([0-9a-f]+)\}'\s*,\s*(GC_[A-Za-z_]+)\s*\)"
)
RUST_STRING = re.compile(r'"((?:[^"\\]|\\.)*)"')


def extract_block(text: str, marker: str, opening: str = "&[") -> str:
    start = text.index(marker)
    start = text.index(opening, start) + len(opening)
    depth = 1
    quote = False
    escape = False
    for index in range(start, len(text)):
        char = text[index]
        if quote:
            if escape:
                escape = False
            elif char == "\\":
                escape = True
            elif char == '"':
                quote = False
            continue
        if char == '"':
            quote = True
        elif char == "[":
            depth += 1
        elif char == "]":
            depth -= 1
            if depth == 0:
                return text[start:index]
    raise ValueError(f"unterminated block after {marker}")


def decode_rust_string(value: str) -> str:
    value = re.sub(r"\\u\{([0-9a-fA-F]+)\}", lambda m: f"\\U{int(m.group(1), 16):08x}", value)
    return ast.literal_eval(f'"{value}"')


def zig_bytes(value: bytes) -> str:
    return ", ".join(f"0x{byte:02x}" for byte in value)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--crate", type=Path, default=DEFAULT_CRATE)
    parser.add_argument("--rope", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()

    tables_text = (args.crate / "src/tables.rs").read_text()
    table_marker = "const grapheme_cat_table: &[(char, char, GraphemeCat)] = &["
    table_start = tables_text.index(table_marker) + len(table_marker)
    table_block = tables_text[table_start : tables_text.index("\n    ];", table_start)]
    ranges = []
    for match in RUST_RANGE.finditer(table_block):
        first, last, rust_property = match.groups()
        if rust_property not in PROPERTY_NAMES:
            raise ValueError(f"unknown grapheme property: {rust_property}")
        ranges.append((int(first, 16), int(last, 16), PROPERTY_NAMES[rust_property]))
    if not ranges:
        raise ValueError("no grapheme ranges found")

    out = [
        "// Generated by tests/generate_grapheme_data.py; do not edit.",
        "// Source: unicode-segmentation 1.13.3, Unicode 17.0.0.",
        "pub const Property = enum { other, cr, lf, control, extend, zwj, regional_indicator, prepend, spacing_mark, l, v, t, lv, lvt, extended_pictographic, incb_consonant };",
        "pub const RangeValue = struct { first: u21, last: u21, property: Property };",
        "pub const ranges = [_]RangeValue{",
    ]
    for first, last, prop in ranges:
        out.append(f"    .{{ .first = 0x{first:x}, .last = 0x{last:x}, .property = .{prop} }},")
    out.append("};\n")
    (args.rope / "src/rope/unicode_grapheme_data.zig").write_text("\n".join(out))

    tests_text = (args.crate / "tests/testdata/mod.rs").read_text()
    vectors_marker = "pub const TEST_SAME: &[(&str, &[&str])] = &["
    vectors_start = tests_text.index(vectors_marker) + len(vectors_marker)
    vectors_block = tests_text[vectors_start : tests_text.index("\n    ];", vectors_start)]
    strings = [decode_rust_string(value) for value in RUST_STRING.findall(vectors_block)]
    def parse_vectors(flat_strings: list[str], fields: int) -> list[tuple[bytes, list[int]]]:
        parsed = []
        cursor = 0
        while cursor < len(flat_strings):
            text = flat_strings[cursor]
            cursor += 1
            alternatives = []
            for _ in range(fields - 1):
                parts = []
                total = 0
                while cursor < len(flat_strings) and total < len(text.encode()):
                    part = flat_strings[cursor]
                    cursor += 1
                    parts.append(part)
                    total += len(part.encode())
                if "".join(parts) != text:
                    raise ValueError("could not reconstruct grapheme test tuple")
                alternatives.append(parts)
            parts = alternatives[0]
            boundaries = [0]
            total = 0
            for part in parts:
                total += len(part.encode())
                boundaries.append(total)
            parsed.append((text.encode(), boundaries))
        return parsed

    vectors = parse_vectors(strings, 2)
    diff_marker = "pub const TEST_DIFF: &[(&str, &[&str], &[&str])] = &["
    diff_start = tests_text.index(diff_marker) + len(diff_marker)
    diff_block = tests_text[diff_start : tests_text.index("\n    ];", diff_start)]
    vectors.extend(parse_vectors([decode_rust_string(value) for value in RUST_STRING.findall(diff_block)], 3))
    # unicode-segmentation keeps two additional extended-grapheme regressions
    # beside the 766 vectors translated from GraphemeBreakTest.txt.
    vectors.extend([
        ("👨‍👧‍👦".encode(), [0, len("👨‍👧‍👦".encode())]),
        ("🤸🏾🏾".encode(), [0, len("🤸🏾🏾".encode())]),
    ])
    if len(vectors) != 768:
        raise ValueError(f"expected 768 embedded vectors, got {len(vectors)}")

    data = bytearray()
    boundaries: list[int] = []
    descriptors = []
    for text, vector_boundaries in vectors:
        data_start = len(data)
        boundary_start = len(boundaries)
        data.extend(text)
        boundaries.extend(vector_boundaries)
        descriptors.append((data_start, len(text), boundary_start, len(vector_boundaries)))

    out = [
        "// Generated by generate_grapheme_data.py; do not edit.",
        "// Source: Unicode 17.0.0 GraphemeBreakTest.txt as embedded by unicode-segmentation 1.13.3.",
        "pub const Vector = struct { data_start: usize, data_len: usize, boundary_start: usize, boundary_len: usize };",
        f"pub const data = [_]u8{{ {zig_bytes(data)} }};",
        "pub const boundaries = [_]u16{ " + ", ".join(map(str, boundaries)) + " };",
        "pub const vectors = [_]Vector{",
    ]
    for data_start, data_len, boundary_start, boundary_len in descriptors:
        out.append(
            f"    .{{ .data_start = {data_start}, .data_len = {data_len}, "
            f".boundary_start = {boundary_start}, .boundary_len = {boundary_len} }},"
        )
    out.append("};\n")
    (args.rope / "tests/grapheme_conformance_data.zig").write_text("\n".join(out))


if __name__ == "__main__":
    main()
