[package]
name = "textmate"
version = "0.1.0"
edition = "2024"

[dependencies]
rope = { path = "../zed/crates/rope" }
text = { path = "../zed/crates/text" }
syntect = { path = "crates/syntect" }
vim-colorscheme = { path = "../vim-colorscheme" }

[dev-dependencies]
clock = { path = "../zed/crates/clock" }
vim-buffer = { path = "../vim-buffer" }
