[metadata]
name = "carbonfox"
description = ""
author = "github/EdenEast"
github = "https://github.com/EdenEast/nightfox.nvim"
type = "dark"

[colors]
c_0 = "#005523"
c_1 = "#08bdba"
c_2 = "#0c0c0c"
c_3 = "#161616"
c_4 = "#172b20"
c_5 = "#182f23"
c_6 = "#1c3433"
c_7 = "#1c3c51"
c_8 = "#222833"
c_9 = "#252525"
c_10 = "#252c39"
c_11 = "#25be6a"
c_12 = "#282828"
c_13 = "#2a2a2a"
c_14 = "#2a7978"
c_15 = "#2b96d9"
c_16 = "#2dc7c4"
c_17 = "#2f2939"
c_18 = "#311d26"
c_19 = "#33b1ff"
c_20 = "#353535"
c_21 = "#361f29"
c_22 = "#3ddbd9"
c_23 = "#46c880"
c_24 = "#47608b"
c_25 = "#484848"
c_26 = "#4f5258"
c_27 = "#525253"
c_28 = "#52bdff"
c_29 = "#535353"
c_30 = "#590008"
c_31 = "#5ae0df"
c_32 = "#6690d9"
c_33 = "#6a568b"
c_34 = "#6b5300"
c_35 = "#6e6f70"
c_36 = "#78a9ff"
c_37 = "#7b7c7e"
c_38 = "#823556"
c_39 = "#8cb6ff"
c_40 = "#8cf8f7"
c_41 = "#a27fd9"
c_42 = "#b3f6c0"
c_43 = "#b6b8bb"
c_44 = "#be95ff"
c_45 = "#bebebe"
c_46 = "#c8a5ff"
c_47 = "#ca4780"
c_48 = "#d96b9b"
c_49 = "#dfdfe0"
c_50 = "#e4e4e5"
c_51 = "#ee5396"
c_52 = "#f16da6"
c_53 = "#f2f4f8"
c_54 = "#f9fbff"
c_55 = "#ff0000"
c_56 = "#ff7eb6"
c_57 = "#ff91c1"
c_58 = "#ffc0b9"

[ui]
background = "c_3"
border_background = "c_3"
border_foreground = "c_2"
caret = "c_3"
cursor_line = "c_20"
cursor_line_nr = "c_44"
diagnostic_error = "c_51"
diagnostic_hint = "c_22"
diagnostic_info = "c_36"
diagnostic_ok = "c_11"
diagnostic_warn = "c_44"
diff_add_background = "c_4"
diff_add_foreground = "c_42"
diff_change_background = "c_8"
diff_change_foreground = "c_40"
diff_delete_background = "c_18"
diff_delete_foreground = "c_58"
diff_text_background = "c_7"
error = "c_51"
find_highlight = "c_22"
find_highlight_foreground = "c_3"
float_background = "c_2"
float_border_background = "c_3"
float_border_foreground = "c_37"
float_foreground = "c_53"
foreground = "c_53"
gutter_foreground = "c_37"
match_paren_background = "c_3"
match_paren_foreground = "c_44"
non_text = "c_29"
pmenu_background = "c_13"
pmenu_foreground = "c_53"
pmenu_sbar = "c_13"
pmenu_sel_background = "c_27"
pmenu_sel_foreground = "c_53"
pmenu_thumb = "c_27"
selection = "c_13"
special_key = "c_29"
statusline_background = "c_2"
statusline_foreground = "c_43"
statusline_nc_background = "c_2"
statusline_nc_foreground = "c_37"
tabline_background = "c_9"
tabline_fill = "c_2"
tabline_foreground = "c_43"
tabline_sel_background = "c_37"
tabline_sel_foreground = "c_3"
warning = "c_44"
whitespace = "c_20"

[syntax]
boolean = "c_22"
character = "c_11"
comment = "c_39"
constant = "c_31"
constructor = "c_19"
delimiter = "c_39"
error = "c_51"
float = "c_22"
function = "c_39"
heading = "c_39"
keyword = "c_57"
link = "c_44"
module = "c_28"
number = "c_22"
operator = "c_43"
property = "c_36"
special = "c_39"
string = "c_11"
tag = "c_39"
tag_attribute = "c_39"
tag_delimiter = "c_28"
todo = "c_3"
type = "c_1"
variable = "c_49"
