[metadata]
name = "catppuccin-latte"
description = ""
author = "github/catppuccin"
github = "https://github.com/catppuccin/nvim"
type = "light"

[colors]
c_0 = "#04a5e5"
c_1 = "#179299"
c_2 = "#1bade7"
c_3 = "#1e66f5"
c_4 = "#209fb5"
c_5 = "#40a02b"
c_6 = "#4c4f69"
c_7 = "#590008"
c_8 = "#6c6f85"
c_9 = "#7287fd"
c_10 = "#7c7f93"
c_11 = "#8839ef"
c_12 = "#8c8fa1"
c_13 = "#9ca0b0"
c_14 = "#a8daf0"
c_15 = "#b0c7f5"
c_16 = "#b3f6c0"
c_17 = "#bcc0cc"
c_18 = "#cbcfd8"
c_19 = "#ccd0da"
c_20 = "#d0e2d1"
c_21 = "#d20f39"
c_22 = "#d9eaf3"
c_23 = "#dae8ec"
c_24 = "#dc8a78"
c_25 = "#dce0e8"
c_26 = "#dd7878"
c_27 = "#df8e1d"
c_28 = "#e0e7f5"
c_29 = "#e64553"
c_30 = "#e6e9ef"
c_31 = "#e9ebf1"
c_32 = "#ea76cb"
c_33 = "#eac8d3"
c_34 = "#ecdce3"
c_35 = "#ede8e0"
c_36 = "#eff1f5"
c_37 = "#fce094"
c_38 = "#fe640b"
c_39 = "#ff0000"
c_40 = "#ffc0b9"

[ui]
background = "c_36"
border_background = "c_36"
border_foreground = "c_25"
caret = "c_36"
cursor_line = "c_31"
cursor_line_nr = "c_9"
diagnostic_error = "c_21"
diagnostic_hint = "c_1"
diagnostic_info = "c_0"
diagnostic_ok = "c_5"
diagnostic_warn = "c_27"
diff_add_background = "c_20"
diff_add_foreground = "c_5"
diff_change_background = "c_28"
diff_change_foreground = "c_3"
diff_delete_background = "c_33"
diff_delete_foreground = "c_7"
diff_text_background = "c_15"
error = "c_21"
find_highlight = "c_2"
find_highlight_foreground = "c_30"
float_background = "c_30"
float_border_background = "c_30"
float_border_foreground = "c_3"
float_foreground = "c_6"
foreground = "c_6"
gutter_foreground = "c_17"
match_paren_background = "c_18"
match_paren_foreground = "c_38"
non_text = "c_13"
pmenu_background = "c_30"
pmenu_foreground = "c_10"
pmenu_sbar = "c_19"
pmenu_sel_background = "c_19"
pmenu_sel_foreground = "c_6"
pmenu_thumb = "c_13"
selection = "c_17"
special_key = "c_13"
statusline_background = "c_30"
statusline_foreground = "c_6"
statusline_nc_background = "c_30"
statusline_nc_foreground = "c_17"
tabline_background = "c_25"
tabline_fill = "c_30"
tabline_foreground = "c_13"
tabline_sel_background = "c_36"
tabline_sel_foreground = "c_6"
warning = "c_27"
whitespace = "c_17"

[syntax]
boolean = "c_38"
character = "c_1"
comment = "c_32"
constant = "c_38"
constructor = "c_27"
delimiter = "c_10"
error = "c_21"
float = "c_38"
function = "c_3"
heading = "c_3"
keyword = "c_32"
link = "c_9"
module = "c_27"
number = "c_38"
operator = "c_0"
property = "c_9"
special = "c_32"
string = "c_5"
tag = "c_3"
tag_attribute = "c_27"
tag_delimiter = "c_1"
todo = "c_36"
type = "c_27"
variable = "c_6"
