[metadata]
name = "catppuccin-frappe"
description = ""
author = "github/catppuccin"
github = "https://github.com/catppuccin/nvim"
type = "dark"

[colors]
c_0 = "#005523"
c_1 = "#232634"
c_2 = "#292c3c"
c_3 = "#303446"
c_4 = "#363c52"
c_5 = "#384251"
c_6 = "#3a4354"
c_7 = "#3b3f52"
c_8 = "#413b4c"
c_9 = "#41424d"
c_10 = "#414559"
c_11 = "#455052"
c_12 = "#474d61"
c_13 = "#4c5778"
c_14 = "#506373"
c_15 = "#514251"
c_16 = "#51576d"
c_17 = "#590008"
c_18 = "#6b5300"
c_19 = "#737994"
c_20 = "#81c8be"
c_21 = "#838ba7"
c_22 = "#85c1dc"
c_23 = "#8caaee"
c_24 = "#8fc1cc"
c_25 = "#949cbb"
c_26 = "#99d1db"
c_27 = "#a5adce"
c_28 = "#a6d189"
c_29 = "#babbf1"
c_30 = "#c6d0f5"
c_31 = "#ca9ee6"
c_32 = "#e5c890"
c_33 = "#e78284"
c_34 = "#ea999c"
c_35 = "#eebebe"
c_36 = "#ef9f76"
c_37 = "#f2d5cf"
c_38 = "#f4b8e4"
c_39 = "#ff0000"
c_40 = "#ffc0b9"

[ui]
background = "c_3"
border_background = "c_3"
border_foreground = "c_1"
caret = "c_3"
cursor_line = "c_7"
cursor_line_nr = "c_29"
diagnostic_error = "c_33"
diagnostic_hint = "c_20"
diagnostic_info = "c_26"
diagnostic_ok = "c_28"
diagnostic_warn = "c_32"
diff_add_background = "c_11"
diff_add_foreground = "c_28"
diff_change_background = "c_4"
diff_change_foreground = "c_23"
diff_delete_background = "c_15"
diff_delete_foreground = "c_40"
diff_text_background = "c_13"
error = "c_33"
find_highlight = "c_24"
find_highlight_foreground = "c_2"
float_background = "c_2"
float_border_background = "c_2"
float_border_foreground = "c_23"
float_foreground = "c_30"
foreground = "c_30"
gutter_foreground = "c_16"
match_paren_background = "c_12"
match_paren_foreground = "c_36"
non_text = "c_19"
pmenu_background = "c_2"
pmenu_foreground = "c_25"
pmenu_sbar = "c_10"
pmenu_sel_background = "c_10"
pmenu_sel_foreground = "c_30"
pmenu_thumb = "c_19"
selection = "c_16"
special_key = "c_19"
statusline_background = "c_2"
statusline_foreground = "c_30"
statusline_nc_background = "c_2"
statusline_nc_foreground = "c_16"
tabline_background = "c_1"
tabline_fill = "c_2"
tabline_foreground = "c_19"
tabline_sel_background = "c_3"
tabline_sel_foreground = "c_30"
warning = "c_32"
whitespace = "c_16"

[syntax]
boolean = "c_36"
character = "c_20"
comment = "c_25"
constant = "c_36"
constructor = "c_32"
delimiter = "c_25"
error = "c_33"
float = "c_36"
function = "c_23"
heading = "c_23"
keyword = "c_31"
link = "c_29"
module = "c_32"
number = "c_36"
operator = "c_26"
property = "c_29"
special = "c_38"
string = "c_28"
tag = "c_29"
tag_attribute = "c_32"
tag_delimiter = "c_20"
todo = "c_3"
type = "c_32"
variable = "c_35"
