[metadata]
name = "catppuccin-macchiato"
description = ""
author = "github/catppuccin"
github = "https://github.com/catppuccin/nvim"
type = "dark"

[colors]
c_0 = "#005523"
c_1 = "#181926"
c_2 = "#1e2030"
c_3 = "#24273a"
c_4 = "#2b3047"
c_5 = "#2e3848"
c_6 = "#2e384a"
c_7 = "#303347"
c_8 = "#363a4f"
c_9 = "#373043"
c_10 = "#373744"
c_11 = "#3b474a"
c_12 = "#3e4257"
c_13 = "#434f72"
c_14 = "#455c6d"
c_15 = "#48384b"
c_16 = "#494d64"
c_17 = "#590008"
c_18 = "#6b5300"
c_19 = "#6e738d"
c_20 = "#7dc4e4"
c_21 = "#8087a2"
c_22 = "#86c5d2"
c_23 = "#8aadf4"
c_24 = "#8bd5ca"
c_25 = "#91d7e3"
c_26 = "#939ab7"
c_27 = "#a5adcb"
c_28 = "#a6da95"
c_29 = "#b7bdf8"
c_30 = "#c6a0f6"
c_31 = "#cad3f5"
c_32 = "#ed8796"
c_33 = "#ee99a0"
c_34 = "#eed49f"
c_35 = "#f0c6c6"
c_36 = "#f4dbd6"
c_37 = "#f5a97f"
c_38 = "#f5bde6"
c_39 = "#ff0000"
c_40 = "#ffc0b9"

[ui]
background = "c_3"
border_background = "c_3"
border_foreground = "c_1"
caret = "c_3"
cursor_line = "c_7"
cursor_line_nr = "c_29"
diagnostic_error = "c_32"
diagnostic_hint = "c_24"
diagnostic_info = "c_25"
diagnostic_ok = "c_28"
diagnostic_warn = "c_34"
diff_add_background = "c_11"
diff_add_foreground = "c_28"
diff_change_background = "c_4"
diff_change_foreground = "c_23"
diff_delete_background = "c_15"
diff_delete_foreground = "c_40"
diff_text_background = "c_13"
error = "c_32"
find_highlight = "c_22"
find_highlight_foreground = "c_2"
float_background = "c_2"
float_border_background = "c_2"
float_border_foreground = "c_23"
float_foreground = "c_31"
foreground = "c_31"
gutter_foreground = "c_16"
match_paren_background = "c_12"
match_paren_foreground = "c_37"
non_text = "c_19"
pmenu_background = "c_2"
pmenu_foreground = "c_26"
pmenu_sbar = "c_8"
pmenu_sel_background = "c_8"
pmenu_sel_foreground = "c_31"
pmenu_thumb = "c_19"
selection = "c_16"
special_key = "c_19"
statusline_background = "c_2"
statusline_foreground = "c_31"
statusline_nc_background = "c_2"
statusline_nc_foreground = "c_16"
tabline_background = "c_1"
tabline_fill = "c_2"
tabline_foreground = "c_19"
tabline_sel_background = "c_3"
tabline_sel_foreground = "c_31"
warning = "c_34"
whitespace = "c_16"

[syntax]
boolean = "c_37"
character = "c_24"
comment = "c_38"
constant = "c_37"
constructor = "c_34"
delimiter = "c_26"
error = "c_32"
float = "c_37"
function = "c_23"
heading = "c_23"
keyword = "c_38"
link = "c_29"
module = "c_34"
number = "c_37"
operator = "c_25"
property = "c_29"
special = "c_38"
string = "c_28"
tag = "c_23"
tag_attribute = "c_34"
tag_delimiter = "c_24"
todo = "c_3"
type = "c_34"
variable = "c_31"
