[metadata]
name = "dawnfox"
description = ""
author = "github/EdenEast"
github = "https://github.com/EdenEast/nightfox.nvim"
type = "light"

[colors]
c_0 = "#005523"
c_1 = "#286983"
c_2 = "#295e73"
c_3 = "#2d81a3"
c_4 = "#4c4769"
c_5 = "#4f5258"
c_6 = "#50848c"
c_7 = "#56949f"
c_8 = "#575279"
c_9 = "#590008"
c_10 = "#5ca7b4"
c_11 = "#5f5695"
c_12 = "#618774"
c_13 = "#625c87"
c_14 = "#629f81"
c_15 = "#6b5300"
c_16 = "#816b9a"
c_17 = "#8cf8f7"
c_18 = "#907aa9"
c_19 = "#91afb8"
c_20 = "#9893a5"
c_21 = "#9a80b9"
c_22 = "#a5576d"
c_23 = "#a6bcc3"
c_24 = "#a8a3b3"
c_25 = "#aebeb1"
c_26 = "#b3f6c0"
c_27 = "#b4637a"
c_28 = "#b8cece"
c_29 = "#bbcacd"
c_30 = "#bdbfc9"
c_31 = "#c26d85"
c_32 = "#c9709e"
c_33 = "#ca6e69"
c_34 = "#ccd3c9"
c_35 = "#d0d8d8"
c_36 = "#d685af"
c_37 = "#d7827e"
c_38 = "#d7acb4"
c_39 = "#dbded5"
c_40 = "#dd9024"
c_41 = "#de8db7"
c_42 = "#e5c9cb"
c_43 = "#e6ebf3"
c_44 = "#ea9d34"
c_45 = "#ebdfe4"
c_46 = "#ebe0df"
c_47 = "#ebe5df"
c_48 = "#ecd7d6"
c_49 = "#eea846"
c_50 = "#f2c991"
c_51 = "#f5dab6"
c_52 = "#faf4ed"
c_53 = "#ff0000"
c_54 = "#ffc0b9"

[ui]
background = "c_52"
border_background = "c_52"
border_foreground = "c_47"
caret = "c_52"
cursor_line = "c_45"
cursor_line_nr = "c_44"
diagnostic_error = "c_27"
diagnostic_hint = "c_12"
diagnostic_info = "c_1"
diagnostic_ok = "c_12"
diagnostic_warn = "c_44"
diff_add_background = "c_39"
diff_add_foreground = "c_26"
diff_change_background = "c_35"
diff_change_foreground = "c_17"
diff_delete_background = "c_48"
diff_delete_foreground = "c_54"
diff_text_background = "c_23"
error = "c_27"
find_highlight = "c_28"
find_highlight_foreground = "c_8"
float_background = "c_47"
float_border_background = "c_52"
float_border_foreground = "c_24"
float_foreground = "c_8"
foreground = "c_8"
gutter_foreground = "c_24"
match_paren_background = "c_52"
match_paren_foreground = "c_44"
non_text = "c_30"
pmenu_background = "c_35"
pmenu_foreground = "c_8"
pmenu_sbar = "c_35"
pmenu_sel_background = "c_28"
pmenu_sel_foreground = "c_8"
pmenu_thumb = "c_28"
selection = "c_35"
special_key = "c_30"
statusline_background = "c_47"
statusline_foreground = "c_13"
statusline_nc_background = "c_47"
statusline_nc_foreground = "c_24"
tabline_background = "c_46"
tabline_fill = "c_47"
tabline_foreground = "c_13"
tabline_sel_background = "c_24"
tabline_sel_foreground = "c_52"
warning = "c_44"
whitespace = "c_45"

[syntax]
boolean = "c_37"
character = "c_12"
comment = "c_2"
constant = "c_33"
constructor = "c_7"
delimiter = "c_2"
error = "c_27"
float = "c_37"
function = "c_2"
heading = "c_2"
keyword = "c_32"
link = "c_18"
module = "c_6"
number = "c_37"
operator = "c_13"
property = "c_1"
special = "c_2"
string = "c_12"
tag = "c_2"
tag_attribute = "c_2"
tag_delimiter = "c_6"
todo = "c_52"
type = "c_44"
variable = "c_8"
