[metadata]
name = "dayfox"
description = ""
author = "github/EdenEast"
github = "https://github.com/EdenEast/nightfox.nvim"
type = "light"

[colors]
c_0 = "#005523"
c_1 = "#223d90"
c_2 = "#22676d"
c_3 = "#2848a9"
c_4 = "#287980"
c_5 = "#302b5d"
c_6 = "#352c24"
c_7 = "#396847"
c_8 = "#3d2b5a"
c_9 = "#4863b6"
c_10 = "#488d93"
c_11 = "#4f5258"
c_12 = "#534c45"
c_13 = "#577f63"
c_14 = "#590008"
c_15 = "#5e2baf"
c_16 = "#643f61"
c_17 = "#6b5300"
c_18 = "#6e33ce"
c_19 = "#7f5152"
c_20 = "#824d5b"
c_21 = "#837a72"
c_22 = "#8452d5"
c_23 = "#8b369a"
c_24 = "#8c1d28"
c_25 = "#8cf8f7"
c_26 = "#8f9dcc"
c_27 = "#924702"
c_28 = "#955f61"
c_29 = "#98ad9b"
c_30 = "#a440b5"
c_31 = "#a4aed2"
c_32 = "#a4c1c2"
c_33 = "#a5222f"
c_34 = "#aab0ad"
c_35 = "#ac5402"
c_36 = "#b25dc0"
c_37 = "#b3434e"
c_38 = "#b3f6c0"
c_39 = "#b86e28"
c_40 = "#b8bfd9"
c_41 = "#bdc9bc"
c_42 = "#cdd0e0"
c_43 = "#ce8a8f"
c_44 = "#d0d6cd"
c_45 = "#d1a378"
c_46 = "#d3c7bb"
c_47 = "#dbd1dd"
c_48 = "#deb4b5"
c_49 = "#e0c3a7"
c_50 = "#e4dcd4"
c_51 = "#e6c8c8"
c_52 = "#e7d2be"
c_53 = "#f4ece6"
c_54 = "#f6f2ee"
c_55 = "#ff0000"
c_56 = "#ffc0b9"

[ui]
background = "c_54"
border_background = "c_54"
border_foreground = "c_50"
caret = "c_54"
cursor_line = "c_46"
cursor_line_nr = "c_35"
diagnostic_error = "c_33"
diagnostic_hint = "c_7"
diagnostic_info = "c_3"
diagnostic_ok = "c_7"
diagnostic_warn = "c_35"
diff_add_background = "c_44"
diff_add_foreground = "c_38"
diff_change_background = "c_42"
diff_change_foreground = "c_25"
diff_delete_background = "c_51"
diff_delete_foreground = "c_56"
diff_text_background = "c_31"
error = "c_33"
find_highlight = "c_7"
find_highlight_foreground = "c_54"
float_background = "c_50"
float_border_background = "c_54"
float_border_foreground = "c_20"
float_foreground = "c_8"
foreground = "c_8"
gutter_foreground = "c_20"
match_paren_background = "c_54"
match_paren_foreground = "c_35"
non_text = "c_34"
pmenu_background = "c_52"
pmenu_foreground = "c_8"
pmenu_sbar = "c_52"
pmenu_sel_background = "c_32"
pmenu_sel_foreground = "c_8"
pmenu_thumb = "c_32"
selection = "c_52"
special_key = "c_34"
statusline_background = "c_50"
statusline_foreground = "c_16"
statusline_nc_background = "c_50"
statusline_nc_foreground = "c_20"
tabline_background = "c_47"
tabline_fill = "c_50"
tabline_foreground = "c_16"
tabline_sel_background = "c_20"
tabline_sel_foreground = "c_54"
warning = "c_35"
whitespace = "c_46"

[syntax]
boolean = "c_28"
character = "c_7"
comment = "c_1"
constant = "c_19"
constructor = "c_4"
delimiter = "c_1"
error = "c_33"
float = "c_28"
function = "c_1"
heading = "c_1"
keyword = "c_23"
link = "c_18"
module = "c_2"
number = "c_28"
operator = "c_16"
property = "c_3"
special = "c_1"
string = "c_7"
tag = "c_18"
tag_attribute = "c_1"
tag_delimiter = "c_2"
todo = "c_54"
type = "c_35"
variable = "c_4"
