[metadata]
name = "dracula"
description = ""
author = "github/Mofiqul"
github = "https://github.com/Mofiqul/dracula.nvim"
type = "dark"

[colors]
c_0 = "#0000ff"
c_1 = "#005523"
c_2 = "#07080d"
c_3 = "#191a21"
c_4 = "#21222c"
c_5 = "#282a36"
c_6 = "#2c453f"
c_7 = "#2f3146"
c_8 = "#3b4048"
c_9 = "#3e4452"
c_10 = "#44475a"
c_11 = "#4f5258"
c_12 = "#50fa7b"
c_13 = "#590008"
c_14 = "#6272a4"
c_15 = "#69ff94"
c_16 = "#6b5300"
c_17 = "#785637"
c_18 = "#808080"
c_19 = "#8be9fd"
c_20 = "#8cf8f7"
c_21 = "#969696"
c_22 = "#9b9ea4"
c_23 = "#a4ffff"
c_24 = "#abb2bf"
c_25 = "#b3f6c0"
c_26 = "#b5629b"
c_27 = "#bd93f9"
c_28 = "#d6acff"
c_29 = "#dd6e6b"
c_30 = "#e0e2ea"
c_31 = "#f1fa8c"
c_32 = "#f8f8f2"
c_33 = "#fce094"
c_34 = "#ff0000"
c_35 = "#ff5555"
c_36 = "#ff6e6e"
c_37 = "#ff79c6"
c_38 = "#ff92df"
c_39 = "#ffb86c"
c_40 = "#ffc0b9"
c_41 = "#ffffff"

[ui]
background = "c_5"
border_background = "c_5"
border_foreground = "c_3"
caret = "c_32"
cursor_line = "c_10"
cursor_line_nr = "c_32"
diagnostic_error = "c_35"
diagnostic_hint = "c_19"
diagnostic_info = "c_19"
diagnostic_ok = "c_25"
diagnostic_warn = "c_31"
diff_add_background = "c_12"
diff_add_foreground = "c_25"
diff_change_background = "c_5"
diff_change_foreground = "c_20"
diff_delete_background = "c_5"
diff_delete_foreground = "c_40"
diff_text_background = "c_5"
diff_text_foreground = "c_14"
error = "c_36"
find_highlight = "c_14"
find_highlight_foreground = "c_39"
float_background = "c_5"
float_border_background = "c_5"
float_border_foreground = "c_24"
float_foreground = "c_32"
foreground = "c_32"
gutter_foreground = "c_14"
match_paren_background = "c_5"
match_paren_foreground = "c_32"
non_text = "c_8"
pmenu_background = "c_4"
pmenu_foreground = "c_24"
pmenu_sbar = "c_5"
pmenu_sel_background = "c_10"
pmenu_sel_foreground = "c_24"
pmenu_thumb = "c_10"
selection = "c_9"
special_key = "c_8"
statusline_background = "c_10"
statusline_foreground = "c_24"
statusline_nc_background = "c_5"
statusline_nc_foreground = "c_14"
tabline_background = "c_5"
tabline_fill = "c_5"
tabline_foreground = "c_14"
tabline_sel_background = "c_5"
tabline_sel_foreground = "c_24"
warning = "c_31"
whitespace = "c_8"

[syntax]
boolean = "c_19"
character = "c_12"
comment = "c_14"
constant = "c_31"
constructor = "c_19"
delimiter = "c_30"
error = "c_36"
float = "c_39"
function = "c_31"
heading = "c_37"
keyword = "c_19"
link = "c_19"
module = "c_39"
number = "c_39"
operator = "c_27"
property = "c_27"
special = "c_12"
string = "c_31"
tag = "c_19"
tag_attribute = "c_12"
tag_delimiter = "c_19"
todo = "c_27"
type = "c_37"
variable = "c_19"
