[metadata]
name = "duskfox"
description = ""
author = "github/EdenEast"
github = "https://github.com/EdenEast/nightfox.nvim"
type = "dark"

[colors]
c_0 = "#005523"
c_1 = "#191726"
c_2 = "#232136"
c_3 = "#2b344a"
c_4 = "#2d2a45"
c_5 = "#2d3a50"
c_6 = "#363943"
c_7 = "#373354"
c_8 = "#37536b"
c_9 = "#393552"
c_10 = "#3d4047"
c_11 = "#3d6078"
c_12 = "#412d44"
c_13 = "#433940"
c_14 = "#433c59"
c_15 = "#47407d"
c_16 = "#4a869c"
c_17 = "#4b3148"
c_18 = "#4b4673"
c_19 = "#4f5258"
c_20 = "#569fba"
c_21 = "#590008"
c_22 = "#63577d"
c_23 = "#637061"
c_24 = "#65b1cd"
c_25 = "#6b5300"
c_26 = "#6e6a86"
c_27 = "#7bb8c1"
c_28 = "#817c9c"
c_29 = "#874864"
c_30 = "#8cf8f7"
c_31 = "#8d7157"
c_32 = "#9ccfd8"
c_33 = "#a3be8c"
c_34 = "#a580d2"
c_35 = "#a6dae3"
c_36 = "#b1acde"
c_37 = "#b1d196"
c_38 = "#b3f6c0"
c_39 = "#c4a7e7"
c_40 = "#ccb1ed"
c_41 = "#cdcbe0"
c_42 = "#d84f76"
c_43 = "#d871a6"
c_44 = "#e0def4"
c_45 = "#e2e0f7"
c_46 = "#ea9a97"
c_47 = "#eae8ff"
c_48 = "#eb6f92"
c_49 = "#eb98c3"
c_50 = "#f083a2"
c_51 = "#f0a4a2"
c_52 = "#f0a6cc"
c_53 = "#f6c177"
c_54 = "#f9cb8c"
c_55 = "#ff0000"
c_56 = "#ffc0b9"

[ui]
background = "c_2"
border_background = "c_2"
border_foreground = "c_1"
caret = "c_2"
cursor_line = "c_7"
cursor_line_nr = "c_53"
diagnostic_error = "c_48"
diagnostic_hint = "c_33"
diagnostic_info = "c_20"
diagnostic_ok = "c_33"
diagnostic_warn = "c_53"
diff_add_background = "c_10"
diff_add_foreground = "c_38"
diff_change_background = "c_5"
diff_change_foreground = "c_30"
diff_delete_background = "c_17"
diff_delete_foreground = "c_56"
diff_text_background = "c_8"
error = "c_48"
find_highlight = "c_33"
find_highlight_foreground = "c_2"
float_background = "c_1"
float_border_background = "c_2"
float_border_foreground = "c_26"
float_foreground = "c_44"
foreground = "c_44"
gutter_foreground = "c_26"
match_paren_background = "c_2"
match_paren_foreground = "c_53"
non_text = "c_18"
pmenu_background = "c_14"
pmenu_foreground = "c_44"
pmenu_sbar = "c_14"
pmenu_sel_background = "c_22"
pmenu_sel_foreground = "c_44"
pmenu_thumb = "c_22"
selection = "c_14"
special_key = "c_18"
statusline_background = "c_1"
statusline_foreground = "c_41"
statusline_nc_background = "c_1"
statusline_nc_foreground = "c_26"
tabline_background = "c_4"
tabline_fill = "c_1"
tabline_foreground = "c_41"
tabline_sel_background = "c_26"
tabline_sel_foreground = "c_2"
warning = "c_53"
whitespace = "c_7"

[syntax]
boolean = "c_46"
character = "c_33"
comment = "c_28"
constant = "c_51"
constructor = "c_32"
delimiter = "c_24"
error = "c_48"
float = "c_46"
function = "c_24"
heading = "c_24"
keyword = "c_40"
link = "c_39"
module = "c_35"
number = "c_46"
operator = "c_41"
property = "c_20"
special = "c_24"
string = "c_33"
tag = "c_24"
tag_attribute = "c_24"
tag_delimiter = "c_35"
todo = "c_2"
type = "c_53"
variable = "c_32"
