[metadata]
name = "gruvbox-material"
description = ""
author = "github/sainnhe"
github = "https://github.com/sainnhe/gruvbox-material"
type = "dark"

[colors]
c_0 = "#005523"
c_1 = "#0e363e"
c_2 = "#1b1b1b"
c_3 = "#282828"
c_4 = "#32302f"
c_5 = "#34381b"
c_6 = "#3a3735"
c_7 = "#3c3836"
c_8 = "#402120"
c_9 = "#45403d"
c_10 = "#4f5258"
c_11 = "#504945"
c_12 = "#590008"
c_13 = "#5a524c"
c_14 = "#6b5300"
c_15 = "#7c6f64"
c_16 = "#7daea3"
c_17 = "#89b482"
c_18 = "#928374"
c_19 = "#a89984"
c_20 = "#a9b665"
c_21 = "#b3f6c0"
c_22 = "#d3869b"
c_23 = "#d4be98"
c_24 = "#d8a657"
c_25 = "#ddc7a1"
c_26 = "#e78a4e"
c_27 = "#ea6962"
c_28 = "#ff0000"

[ui]
background = "c_3"
border_background = "c_3"
border_foreground = "c_13"
caret = "c_3"
cursor_line = "c_4"
cursor_line_nr = "c_18"
diagnostic_error = "c_27"
diagnostic_hint = "c_22"
diagnostic_info = "c_16"
diagnostic_ok = "c_20"
diagnostic_warn = "c_24"
diff_add_background = "c_5"
diff_add_foreground = "c_20"
diff_change_background = "c_1"
diff_change_foreground = "c_16"
diff_delete_background = "c_8"
diff_delete_foreground = "c_27"
diff_text_background = "c_16"
diff_text_foreground = "c_3"
error = "c_27"
find_highlight = "c_20"
find_highlight_foreground = "c_3"
float_background = "c_9"
float_border_background = "c_9"
float_border_foreground = "c_18"
float_foreground = "c_25"
foreground = "c_23"
gutter_foreground = "c_13"
match_paren_background = "c_9"
match_paren_foreground = "c_23"
non_text = "c_13"
pmenu_background = "c_9"
pmenu_foreground = "c_25"
pmenu_sbar = "c_9"
pmenu_sel_background = "c_19"
pmenu_sel_foreground = "c_9"
pmenu_thumb = "c_15"
selection = "c_9"
special_key = "c_26"
statusline_background = "c_4"
statusline_foreground = "c_25"
statusline_nc_background = "c_4"
statusline_nc_foreground = "c_18"
tabline_background = "c_11"
tabline_fill = "c_4"
tabline_foreground = "c_25"
tabline_sel_background = "c_19"
tabline_sel_foreground = "c_3"
warning = "c_24"
whitespace = "c_13"

[syntax]
boolean = "c_22"
character = "c_20"
comment = "c_18"
constant = "c_17"
constructor = "c_20"
delimiter = "c_23"
error = "c_27"
float = "c_22"
function = "c_20"
heading = "c_26"
keyword = "c_27"
link = "c_17"
module = "c_24"
number = "c_22"
operator = "c_26"
property = "c_16"
special = "c_24"
string = "c_20"
tag = "c_26"
tag_attribute = "c_20"
tag_delimiter = "c_20"
todo = "c_3"
type = "c_24"
variable = "c_16"
