[metadata]
name = "nightfox"
description = ""
author = "github/EdenEast"
github = "https://github.com/EdenEast/nightfox.nvim"
type = "dark"

[colors]
c_0 = "#005523"
c_1 = "#131a24"
c_2 = "#192330"
c_3 = "#212e3f"
c_4 = "#243244"
c_5 = "#253f4a"
c_6 = "#26343c"
c_7 = "#29394f"
c_8 = "#2b3b51"
c_9 = "#2e4045"
c_10 = "#2f2837"
c_11 = "#393b44"
c_12 = "#39506d"
c_13 = "#3c2c3c"
c_14 = "#3c5372"
c_15 = "#40423e"
c_16 = "#456083"
c_17 = "#4d6b65"
c_18 = "#4f5258"
c_19 = "#54aeb0"
c_20 = "#575860"
c_21 = "#590008"
c_22 = "#6085b6"
c_23 = "#63cdcf"
c_24 = "#6b5300"
c_25 = "#71394f"
c_26 = "#71839b"
c_27 = "#719cd6"
c_28 = "#738091"
c_29 = "#7a7252"
c_30 = "#7ad5d6"
c_31 = "#81b29a"
c_32 = "#8567b6"
c_33 = "#86abdc"
c_34 = "#8cf8f7"
c_35 = "#8ebaa4"
c_36 = "#9d79d6"
c_37 = "#ab435d"
c_38 = "#aeafb0"
c_39 = "#b3f6c0"
c_40 = "#b668b3"
c_41 = "#baa1e2"
c_42 = "#bebebe"
c_43 = "#c94f6d"
c_44 = "#cdcecf"
c_45 = "#d16983"
c_46 = "#d67ad2"
c_47 = "#d6d6d7"
c_48 = "#dbc074"
c_49 = "#dc8ed9"
c_50 = "#dfdfe0"
c_51 = "#e0c989"
c_52 = "#e4e4e5"
c_53 = "#f4a261"
c_54 = "#f6b079"
c_55 = "#ff0000"
c_56 = "#ffc0b9"

[ui]
background = "c_2"
border_background = "c_2"
border_foreground = "c_1"
caret = "c_2"
cursor_line = "c_7"
cursor_line_nr = "c_48"
diagnostic_error = "c_43"
diagnostic_hint = "c_31"
diagnostic_info = "c_27"
diagnostic_ok = "c_31"
diagnostic_warn = "c_48"
diff_add_background = "c_6"
diff_add_foreground = "c_39"
diff_change_background = "c_4"
diff_change_foreground = "c_34"
diff_delete_background = "c_10"
diff_delete_foreground = "c_56"
diff_text_background = "c_5"
error = "c_43"
find_highlight = "c_31"
find_highlight_foreground = "c_2"
float_background = "c_1"
float_border_background = "c_2"
float_border_foreground = "c_26"
float_foreground = "c_44"
foreground = "c_44"
gutter_foreground = "c_26"
match_paren_background = "c_2"
match_paren_foreground = "c_48"
non_text = "c_12"
pmenu_background = "c_8"
pmenu_foreground = "c_44"
pmenu_sbar = "c_8"
pmenu_sel_background = "c_14"
pmenu_sel_foreground = "c_44"
pmenu_thumb = "c_14"
selection = "c_8"
special_key = "c_12"
statusline_background = "c_1"
statusline_foreground = "c_38"
statusline_nc_background = "c_1"
statusline_nc_foreground = "c_26"
tabline_background = "c_3"
tabline_fill = "c_1"
tabline_foreground = "c_38"
tabline_sel_background = "c_26"
tabline_sel_foreground = "c_2"
warning = "c_48"
whitespace = "c_7"

[syntax]
boolean = "c_53"
character = "c_31"
comment = "c_33"
constant = "c_54"
constructor = "c_23"
delimiter = "c_33"
error = "c_43"
float = "c_53"
function = "c_33"
heading = "c_33"
keyword = "c_49"
link = "c_36"
module = "c_30"
number = "c_53"
operator = "c_38"
property = "c_27"
special = "c_33"
string = "c_31"
tag = "c_36"
tag_attribute = "c_33"
tag_delimiter = "c_30"
todo = "c_2"
type = "c_48"
variable = "c_50"
