[metadata]
name = "nordfox"
description = ""
author = "github/EdenEast"
github = "https://github.com/EdenEast/nightfox.nvim"
type = "dark"

[colors]
c_0 = "#005523"
c_1 = "#232831"
c_2 = "#2e3440"
c_3 = "#364150"
c_4 = "#39404f"
c_5 = "#3b4252"
c_6 = "#3c4548"
c_7 = "#3d515f"
c_8 = "#3e4a5b"
c_9 = "#3f4a5a"
c_10 = "#403843"
c_11 = "#444c5e"
c_12 = "#45504f"
c_13 = "#465780"
c_14 = "#4b3d48"
c_15 = "#4f5258"
c_16 = "#4f6074"
c_17 = "#54524f"
c_18 = "#586a81"
c_19 = "#590008"
c_20 = "#5a657d"
c_21 = "#60728a"
c_22 = "#668aab"
c_23 = "#697966"
c_24 = "#69a7ba"
c_25 = "#6b5300"
c_26 = "#774a55"
c_27 = "#7e8188"
c_28 = "#81a1c1"
c_29 = "#88c0d0"
c_30 = "#8c7f66"
c_31 = "#8cafd2"
c_32 = "#8cf8f7"
c_33 = "#93ccdc"
c_34 = "#9d7495"
c_35 = "#a3be8c"
c_36 = "#a54e56"
c_37 = "#a96ca5"
c_38 = "#abb1bb"
c_39 = "#b1d196"
c_40 = "#b3f6c0"
c_41 = "#b48ead"
c_42 = "#bbc3d4"
c_43 = "#bf616a"
c_44 = "#bf88bc"
c_45 = "#c7cdd9"
c_46 = "#c895bf"
c_47 = "#c9826b"
c_48 = "#cdcecf"
c_49 = "#d06f79"
c_50 = "#d092ce"
c_51 = "#d89079"
c_52 = "#e5e9f0"
c_53 = "#e7ecf4"
c_54 = "#ebcb8b"
c_55 = "#f0d399"
c_56 = "#ff0000"
c_57 = "#ffc0b9"

[ui]
background = "c_2"
border_background = "c_2"
border_foreground = "c_1"
caret = "c_2"
cursor_line = "c_11"
cursor_line_nr = "c_54"
diagnostic_error = "c_43"
diagnostic_hint = "c_35"
diagnostic_info = "c_28"
diagnostic_ok = "c_35"
diagnostic_warn = "c_54"
diff_add_background = "c_6"
diff_add_foreground = "c_40"
diff_change_background = "c_3"
diff_change_foreground = "c_32"
diff_delete_background = "c_10"
diff_delete_foreground = "c_57"
diff_text_background = "c_7"
error = "c_43"
find_highlight = "c_35"
find_highlight_foreground = "c_2"
float_background = "c_1"
float_border_background = "c_2"
float_border_foreground = "c_27"
float_foreground = "c_48"
foreground = "c_48"
gutter_foreground = "c_27"
match_paren_background = "c_2"
match_paren_foreground = "c_54"
non_text = "c_20"
pmenu_background = "c_8"
pmenu_foreground = "c_48"
pmenu_sbar = "c_8"
pmenu_sel_background = "c_16"
pmenu_sel_foreground = "c_48"
pmenu_thumb = "c_16"
selection = "c_8"
special_key = "c_20"
statusline_background = "c_1"
statusline_foreground = "c_38"
statusline_nc_background = "c_1"
statusline_nc_foreground = "c_27"
tabline_background = "c_4"
tabline_fill = "c_1"
tabline_foreground = "c_38"
tabline_sel_background = "c_27"
tabline_sel_foreground = "c_2"
warning = "c_54"
whitespace = "c_11"

[syntax]
boolean = "c_47"
character = "c_35"
comment = "c_21"
constant = "c_51"
constructor = "c_29"
delimiter = "c_31"
error = "c_43"
float = "c_47"
function = "c_31"
heading = "c_31"
keyword = "c_50"
link = "c_41"
module = "c_33"
number = "c_47"
operator = "c_38"
property = "c_28"
special = "c_31"
string = "c_35"
tag = "c_41"
tag_attribute = "c_31"
tag_delimiter = "c_33"
todo = "c_2"
type = "c_54"
variable = "c_29"
