[metadata]
name = "onedark"
description = ""
author = "github/navarasu"
github = "https://github.com/navarasu/onedark.nvim"
type = "dark"

[colors]
c_0 = "#005523"
c_1 = "#1c3448"
c_2 = "#21252b"
c_3 = "#282c34"
c_4 = "#28333b"
c_5 = "#2b6f77"
c_6 = "#2c5372"
c_7 = "#2d323a"
c_8 = "#31353f"
c_9 = "#31392b"
c_10 = "#314050"
c_11 = "#322e3f"
c_12 = "#332d35"
c_13 = "#333232"
c_14 = "#333b3b"
c_15 = "#364d63"
c_16 = "#382b2c"
c_17 = "#393739"
c_18 = "#393f4a"
c_19 = "#39433e"
c_20 = "#3b3f4c"
c_21 = "#40374d"
c_22 = "#445245"
c_23 = "#447aa7"
c_24 = "#4f5258"
c_25 = "#503f5e"
c_26 = "#56b6c2"
c_27 = "#590008"
c_28 = "#5c6370"
c_29 = "#61afef"
c_30 = "#6b5300"
c_31 = "#73b8f1"
c_32 = "#848b98"
c_33 = "#8a3fa0"
c_34 = "#93691d"
c_35 = "#98c379"
c_36 = "#993939"
c_37 = "#abb2bf"
c_38 = "#b3f6c0"
c_39 = "#c678dd"
c_40 = "#d19a66"
c_41 = "#e5c07b"
c_42 = "#e86671"
c_43 = "#ebd09c"
c_44 = "#ff0000"

[ui]
background = "c_3"
border_background = "c_3"
border_foreground = "c_20"
caret = "c_37"
cursor_line = "c_8"
cursor_line_nr = "c_37"
diagnostic_error = "c_42"
diagnostic_hint = "c_39"
diagnostic_info = "c_26"
diagnostic_ok = "c_35"
diagnostic_warn = "c_41"
diff_add_background = "c_9"
diff_add_foreground = "c_35"
diff_change_background = "c_1"
diff_change_foreground = "c_29"
diff_delete_background = "c_16"
diff_delete_foreground = "c_42"
diff_text_background = "c_6"
error = "c_42"
find_highlight = "c_8"
find_highlight_foreground = "c_3"
float_background = "c_8"
float_border_background = "c_8"
float_border_foreground = "c_28"
float_foreground = "c_37"
foreground = "c_37"
gutter = "c_8"
gutter_foreground = "c_28"
match_paren_background = "c_20"
match_paren_foreground = "c_37"
non_text = "c_28"
pmenu_background = "c_8"
pmenu_foreground = "c_37"
pmenu_sbar = "c_8"
pmenu_sel_background = "c_31"
pmenu_sel_foreground = "c_3"
pmenu_thumb = "c_28"
selection = "c_20"
special_key = "c_28"
statusline_background = "c_18"
statusline_foreground = "c_37"
statusline_nc_background = "c_8"
statusline_nc_foreground = "c_28"
tabline_background = "c_8"
tabline_fill = "c_8"
tabline_foreground = "c_37"
tabline_sel_background = "c_37"
tabline_sel_foreground = "c_3"
warning = "c_41"
whitespace = "c_28"

[syntax]
boolean = "c_40"
character = "c_40"
comment = "c_28"
constant = "c_26"
constructor = "c_41"
delimiter = "c_32"
error = "c_39"
float = "c_40"
function = "c_29"
heading = "c_40"
keyword = "c_39"
link = "c_29"
module = "c_41"
number = "c_40"
operator = "c_39"
property = "c_26"
special = "c_42"
string = "c_35"
tag = "c_39"
tag_attribute = "c_41"
tag_delimiter = "c_39"
todo = "c_42"
type = "c_41"
variable = "c_42"
