[metadata]
name = "rose-pine"
description = ""
author = "github/rose-pine"
github = "https://github.com/rose-pine/neovim"
type = "dark"

[colors]
c_0 = "#232136"
c_1 = "#27253b"
c_2 = "#273248"
c_3 = "#28374e"
c_4 = "#2a273f"
c_5 = "#2a283e"
c_6 = "#2a3d55"
c_7 = "#2b283e"
c_8 = "#2e2f42"
c_9 = "#2f3246"
c_10 = "#332e48"
c_11 = "#33637f"
c_12 = "#353b4e"
c_13 = "#37293f"
c_14 = "#38313d"
c_15 = "#393552"
c_16 = "#3a3e4e"
c_17 = "#3b3551"
c_18 = "#3b4456"
c_19 = "#3e8fb0"
c_20 = "#413345"
c_21 = "#433c59"
c_22 = "#44415a"
c_23 = "#4b3148"
c_24 = "#4b3949"
c_25 = "#4d4143"
c_26 = "#4f5258"
c_27 = "#56526e"
c_28 = "#6e6a86"
c_29 = "#73515d"
c_30 = "#908caa"
c_31 = "#95b1ac"
c_32 = "#9ccfd8"
c_33 = "#b3f6c0"
c_34 = "#c4a7e7"
c_35 = "#e0def4"
c_36 = "#ea9a97"
c_37 = "#eb6f92"
c_38 = "#f6c177"

[ui]
background = "c_0"
border_background = "c_0"
border_foreground = "c_28"
caret = "c_35"
cursor_line = "c_15"
cursor_line_nr = "c_35"
diagnostic_error = "c_37"
diagnostic_hint = "c_34"
diagnostic_info = "c_32"
diagnostic_ok = "c_31"
diagnostic_warn = "c_38"
diff_add_background = "c_18"
diff_add_foreground = "c_32"
diff_change_background = "c_24"
diff_change_foreground = "c_36"
diff_delete_background = "c_23"
diff_delete_foreground = "c_37"
diff_text_background = "c_29"
error = "c_37"
find_highlight = "c_25"
find_highlight_foreground = "c_35"
float_background = "c_4"
float_border_background = "c_4"
float_border_foreground = "c_28"
float_foreground = "c_35"
foreground = "c_35"
gutter_foreground = "c_28"
match_paren_background = "c_6"
match_paren_foreground = "c_19"
non_text = "c_28"
pmenu_background = "c_4"
pmenu_foreground = "c_30"
pmenu_sbar = "c_4"
pmenu_sel_background = "c_15"
pmenu_sel_foreground = "c_35"
pmenu_thumb = "c_28"
selection = "c_17"
special_key = "c_32"
statusline_background = "c_4"
statusline_foreground = "c_30"
statusline_nc_background = "c_1"
statusline_nc_foreground = "c_28"
tabline_background = "c_4"
tabline_fill = "c_4"
tabline_foreground = "c_30"
tabline_sel_background = "c_15"
tabline_sel_foreground = "c_35"
warning = "c_38"
whitespace = "c_28"

[syntax]
boolean = "c_36"
character = "c_38"
comment = "c_30"
constant = "c_38"
constructor = "c_32"
delimiter = "c_30"
error = "c_37"
float = "c_38"
function = "c_36"
heading = "c_32"
keyword = "c_19"
link = "c_34"
module = "c_35"
number = "c_38"
operator = "c_30"
property = "c_32"
special = "c_32"
string = "c_38"
tag = "c_32"
tag_attribute = "c_34"
tag_delimiter = "c_30"
todo = "c_36"
type = "c_32"
variable = "c_35"
