[metadata]
name = "rose-pine"
description = ""
author = "github/rose-pine"
github = "https://github.com/rose-pine/neovim"
type = "dark"

[colors]
c_0 = "#191724"
c_1 = "#1d1b2a"
c_2 = "#1d2534"
c_3 = "#1e2a39"
c_4 = "#1f1d2e"
c_5 = "#1f2e3f"
c_6 = "#21202e"
c_7 = "#221f2e"
c_8 = "#252632"
c_9 = "#26233a"
c_10 = "#262936"
c_11 = "#274f64"
c_12 = "#2a2538"
c_13 = "#2d333f"
c_14 = "#2e202f"
c_15 = "#2f282c"
c_16 = "#31748f"
c_17 = "#32363f"
c_18 = "#332d41"
c_19 = "#333c48"
c_20 = "#39303b"
c_21 = "#3b344b"
c_22 = "#403d52"
c_23 = "#43293a"
c_24 = "#433842"
c_25 = "#453935"
c_26 = "#4f5258"
c_27 = "#524f67"
c_28 = "#6d5960"
c_29 = "#6e6a86"
c_30 = "#908caa"
c_31 = "#95b1ac"
c_32 = "#9ccfd8"
c_33 = "#b3f6c0"
c_34 = "#c4a7e7"
c_35 = "#e0def4"
c_36 = "#eb6f92"
c_37 = "#ebbcba"
c_38 = "#f6c177"

[ui]
background = "c_0"
border_background = "c_0"
border_foreground = "c_29"
caret = "c_35"
cursor_line = "c_9"
cursor_line_nr = "c_35"
diagnostic_error = "c_36"
diagnostic_hint = "c_34"
diagnostic_info = "c_32"
diagnostic_ok = "c_31"
diagnostic_warn = "c_38"
diff_add_background = "c_19"
diff_add_foreground = "c_32"
diff_change_background = "c_24"
diff_change_foreground = "c_37"
diff_delete_background = "c_23"
diff_delete_foreground = "c_36"
diff_text_background = "c_28"
error = "c_36"
find_highlight = "c_25"
find_highlight_foreground = "c_35"
float_background = "c_4"
float_border_background = "c_4"
float_border_foreground = "c_29"
float_foreground = "c_35"
foreground = "c_35"
gutter_foreground = "c_29"
match_paren_background = "c_5"
match_paren_foreground = "c_16"
non_text = "c_29"
pmenu_background = "c_4"
pmenu_foreground = "c_30"
pmenu_sbar = "c_4"
pmenu_sel_background = "c_9"
pmenu_sel_foreground = "c_35"
pmenu_thumb = "c_29"
selection = "c_18"
special_key = "c_32"
statusline_background = "c_4"
statusline_foreground = "c_30"
statusline_nc_background = "c_1"
statusline_nc_foreground = "c_29"
tabline_background = "c_4"
tabline_fill = "c_4"
tabline_foreground = "c_30"
tabline_sel_background = "c_9"
tabline_sel_foreground = "c_35"
warning = "c_38"
whitespace = "c_29"

[syntax]
boolean = "c_37"
character = "c_38"
comment = "c_30"
constant = "c_38"
constructor = "c_32"
delimiter = "c_30"
error = "c_36"
float = "c_38"
function = "c_37"
heading = "c_32"
keyword = "c_16"
link = "c_34"
module = "c_35"
number = "c_38"
operator = "c_30"
property = "c_32"
special = "c_32"
string = "c_38"
tag = "c_32"
tag_attribute = "c_34"
tag_delimiter = "c_30"
todo = "c_37"
type = "c_32"
variable = "c_35"
