[metadata]
name = "rose-pine"
description = ""
author = "github/rose-pine"
github = "https://github.com/rose-pine/neovim"
type = "light"

[colors]
c_0 = "#286983"
c_1 = "#464261"
c_2 = "#4f5258"
c_3 = "#56949f"
c_4 = "#6d8f89"
c_5 = "#797593"
c_6 = "#7ca1ad"
c_7 = "#907aa9"
c_8 = "#9893a5"
c_9 = "#b3f6c0"
c_10 = "#b4637a"
c_11 = "#c6d1d3"
c_12 = "#cecacd"
c_13 = "#d0d8d8"
c_14 = "#d7827e"
c_15 = "#d9e1dd"
c_16 = "#dbdfdd"
c_17 = "#dee0d9"
c_18 = "#dfdad9"
c_19 = "#e1e6e1"
c_20 = "#e5dcdf"
c_21 = "#ea9d34"
c_22 = "#eae2e3"
c_23 = "#eaeae5"
c_24 = "#ecc6c1"
c_25 = "#ecd7d6"
c_26 = "#eceae3"
c_27 = "#efe8e6"
c_28 = "#f0eae6"
c_29 = "#f2e9e1"
c_30 = "#f3ddd7"
c_31 = "#f3e6e2"
c_32 = "#f4ede8"
c_33 = "#f5e3dc"
c_34 = "#f7e3c8"
c_35 = "#f8ebdb"
c_36 = "#faf4ed"
c_37 = "#fdf8f1"
c_38 = "#fffaf3"

[ui]
background = "c_36"
border_background = "c_36"
border_foreground = "c_8"
caret = "c_1"
cursor_line = "c_29"
cursor_line_nr = "c_1"
diagnostic_error = "c_10"
diagnostic_hint = "c_7"
diagnostic_info = "c_3"
diagnostic_ok = "c_4"
diagnostic_warn = "c_21"
diff_add_background = "c_15"
diff_add_foreground = "c_3"
diff_change_background = "c_30"
diff_change_foreground = "c_14"
diff_delete_background = "c_25"
diff_delete_foreground = "c_10"
diff_text_background = "c_24"
error = "c_10"
find_highlight = "c_34"
find_highlight_foreground = "c_1"
float_background = "c_38"
float_border_background = "c_38"
float_border_foreground = "c_8"
float_foreground = "c_1"
foreground = "c_1"
gutter_foreground = "c_8"
match_paren_background = "c_11"
match_paren_foreground = "c_0"
non_text = "c_8"
pmenu_background = "c_38"
pmenu_foreground = "c_5"
pmenu_sbar = "c_38"
pmenu_sel_background = "c_29"
pmenu_sel_foreground = "c_1"
pmenu_thumb = "c_8"
selection = "c_22"
special_key = "c_3"
statusline_background = "c_38"
statusline_foreground = "c_5"
statusline_nc_background = "c_37"
statusline_nc_foreground = "c_8"
tabline_background = "c_38"
tabline_fill = "c_38"
tabline_foreground = "c_5"
tabline_sel_background = "c_29"
tabline_sel_foreground = "c_1"
warning = "c_21"
whitespace = "c_8"

[syntax]
boolean = "c_14"
character = "c_21"
comment = "c_5"
constant = "c_21"
constructor = "c_3"
delimiter = "c_5"
error = "c_10"
float = "c_21"
function = "c_14"
heading = "c_3"
keyword = "c_0"
link = "c_7"
module = "c_1"
number = "c_21"
operator = "c_5"
property = "c_3"
special = "c_3"
string = "c_21"
tag = "c_3"
tag_attribute = "c_7"
tag_delimiter = "c_5"
todo = "c_14"
type = "c_3"
variable = "c_1"
