[metadata]
name = "terafox"
description = ""
author = "github/EdenEast"
github = "https://github.com/EdenEast/nightfox.nvim"
type = "dark"

[colors]
c_0 = "#005523"
c_1 = "#0f1c1e"
c_2 = "#152528"
c_3 = "#1d3337"
c_4 = "#1f353c"
c_5 = "#24383a"
c_6 = "#254147"
c_7 = "#293e40"
c_8 = "#2d4f56"
c_9 = "#2f3239"
c_10 = "#31474b"
c_11 = "#352d2e"
c_12 = "#383835"
c_13 = "#385c69"
c_14 = "#425e5e"
c_15 = "#466066"
c_16 = "#486565"
c_17 = "#4a3332"
c_18 = "#4d7d90"
c_19 = "#4e5157"
c_20 = "#4f5258"
c_21 = "#587b7b"
c_22 = "#590008"
c_23 = "#5a93aa"
c_24 = "#6b5300"
c_25 = "#6d7f8b"
c_26 = "#73a3b7"
c_27 = "#7aa4a1"
c_28 = "#7e413d"
c_29 = "#896554"
c_30 = "#89aeb8"
c_31 = "#8cf8f7"
c_32 = "#8eb2af"
c_33 = "#934e69"
c_34 = "#a1cdd8"
c_35 = "#ad5c7c"
c_36 = "#ad6771"
c_37 = "#afd4de"
c_38 = "#b3f6c0"
c_39 = "#b97490"
c_40 = "#c54e45"
c_41 = "#c8c8c8"
c_42 = "#cb7985"
c_43 = "#cbd9d8"
c_44 = "#d38d97"
c_45 = "#e6eaea"
c_46 = "#e85c51"
c_47 = "#eaeeee"
c_48 = "#eb746b"
c_49 = "#ebebeb"
c_50 = "#eeeeee"
c_51 = "#fda47f"
c_52 = "#fdb292"
c_53 = "#ff0000"
c_54 = "#ff8349"
c_55 = "#ff9664"
c_56 = "#ffc0b9"

[ui]
background = "c_2"
border_background = "c_2"
border_foreground = "c_1"
caret = "c_2"
cursor_line = "c_6"
cursor_line_nr = "c_51"
diagnostic_error = "c_46"
diagnostic_hint = "c_27"
diagnostic_info = "c_23"
diagnostic_ok = "c_27"
diagnostic_warn = "c_51"
diff_add_background = "c_7"
diff_add_foreground = "c_38"
diff_change_background = "c_10"
diff_change_foreground = "c_31"
diff_delete_background = "c_17"
diff_delete_foreground = "c_56"
diff_text_background = "c_15"
error = "c_46"
find_highlight = "c_27"
find_highlight_foreground = "c_2"
float_background = "c_1"
float_border_background = "c_2"
float_border_foreground = "c_21"
float_foreground = "c_45"
foreground = "c_45"
gutter_foreground = "c_21"
match_paren_background = "c_2"
match_paren_foreground = "c_51"
non_text = "c_8"
pmenu_background = "c_7"
pmenu_foreground = "c_45"
pmenu_sbar = "c_7"
pmenu_sel_background = "c_14"
pmenu_sel_foreground = "c_45"
pmenu_thumb = "c_14"
selection = "c_7"
special_key = "c_8"
statusline_background = "c_1"
statusline_foreground = "c_43"
statusline_nc_background = "c_1"
statusline_nc_foreground = "c_21"
tabline_background = "c_3"
tabline_fill = "c_1"
tabline_foreground = "c_43"
tabline_sel_background = "c_21"
tabline_sel_foreground = "c_2"
warning = "c_51"
whitespace = "c_6"

[syntax]
boolean = "c_54"
character = "c_27"
comment = "c_26"
constant = "c_55"
constructor = "c_34"
delimiter = "c_26"
error = "c_46"
float = "c_54"
function = "c_26"
heading = "c_26"
keyword = "c_39"
link = "c_35"
module = "c_37"
number = "c_54"
operator = "c_43"
property = "c_23"
special = "c_26"
string = "c_27"
tag = "c_35"
tag_attribute = "c_26"
tag_delimiter = "c_37"
todo = "c_2"
type = "c_51"
variable = "c_49"
