[metadata]
name = "tokyonight-storm"
description = ""
author = "github/folke"
github = "https://github.com/folke/tokyonight.nvim"
type = "dark"

[colors]
c_0 = "#005523"
c_1 = "#0db9d7"
c_2 = "#129cb8"
c_3 = "#167f99"
c_4 = "#191c2a"
c_5 = "#1abc9c"
c_6 = "#1b6279"
c_7 = "#1c9e89"
c_8 = "#1d202f"
c_9 = "#1d546a"
c_10 = "#1f2335"
c_11 = "#22374b"
c_12 = "#232f40"
c_13 = "#233745"
c_14 = "#24283b"
c_15 = "#25384b"
c_16 = "#262a3e"
c_17 = "#262c40"
c_18 = "#26576c"
c_19 = "#272b3f"
c_20 = "#272d43"
c_21 = "#282d41"
c_22 = "#282e44"
c_23 = "#28304b"
c_24 = "#292e42"
c_25 = "#29a4bd"
c_26 = "#2a2c43"
c_27 = "#2a303d"
c_28 = "#2a334b"
c_29 = "#2ac3de"
c_30 = "#2b485a"
c_31 = "#2c2e44"
c_32 = "#2d2f3d"
c_33 = "#2d344e"
c_34 = "#2e3c64"
c_35 = "#2f2c3f"
c_36 = "#2f2e3d"
c_37 = "#30304b"
c_38 = "#30354e"
c_39 = "#303940"
c_40 = "#33334e"
c_41 = "#333952"
c_42 = "#362c3d"
c_43 = "#363d59"
c_44 = "#373640"
c_45 = "#383e5a"
c_46 = "#393043"
c_47 = "#394b70"
c_48 = "#3a343f"
c_49 = "#3b4261"
c_50 = "#3d59a1"
c_51 = "#3e8695"
c_52 = "#414868"
c_53 = "#41a6b5"
c_54 = "#449dab"
c_55 = "#48416a"
c_56 = "#4f5258"
c_57 = "#52313f"
c_58 = "#544a7a"
c_59 = "#545c7e"
c_60 = "#5571a1"
c_61 = "#565f89"
c_62 = "#57c5e5"
c_63 = "#590008"
c_64 = "#5b3340"
c_65 = "#5c5149"
c_66 = "#607dbf"
c_67 = "#6183bb"
c_68 = "#636a8d"
c_69 = "#6b5300"
c_70 = "#6d3641"
c_71 = "#6f5e4d"
c_72 = "#737aa2"
c_73 = "#73daca"
c_74 = "#7aa2f7"
c_75 = "#7b454f"
c_76 = "#7dcfff"
c_77 = "#89ddff"
c_78 = "#8cf8f7"
c_79 = "#914c54"
c_80 = "#9d7cd8"
c_81 = "#9ece6a"
c_82 = "#a8875b"
c_83 = "#a9b1d6"
c_84 = "#b3f6c0"
c_85 = "#b4f9f8"
c_86 = "#b64448"
c_87 = "#ba945f"
c_88 = "#bb9af7"
c_89 = "#c0caf5"
c_90 = "#dab484"
c_91 = "#db4b4b"
c_92 = "#e0af68"
c_93 = "#f7768e"
c_94 = "#ff0000"
c_95 = "#ff007c"
c_96 = "#ff9e64"
c_97 = "#ffc0b9"
c_98 = "#ffffff"

[ui]
background = "c_14"
border_background = "c_14"
border_foreground = "c_8"
caret = "c_14"
cursor_line = "c_24"
cursor_line_nr = "c_96"
diagnostic_error = "c_91"
diagnostic_hint = "c_5"
diagnostic_info = "c_1"
diagnostic_ok = "c_84"
diagnostic_warn = "c_92"
diff_add_background = "c_30"
diff_add_foreground = "c_84"
diff_change_background = "c_20"
diff_change_foreground = "c_78"
diff_delete_background = "c_57"
diff_delete_foreground = "c_97"
diff_text_background = "c_47"
error = "c_91"
find_highlight = "c_50"
find_highlight_foreground = "c_89"
float_background = "c_10"
float_border_background = "c_10"
float_border_foreground = "c_25"
float_foreground = "c_89"
foreground = "c_89"
gutter = "c_14"
gutter_foreground = "c_49"
match_paren_background = "c_14"
match_paren_foreground = "c_96"
non_text = "c_59"
pmenu_background = "c_10"
pmenu_foreground = "c_89"
pmenu_sbar = "c_19"
pmenu_sel_background = "c_43"
pmenu_sel_foreground = "c_89"
pmenu_thumb = "c_49"
selection = "c_34"
special_key = "c_59"
statusline_background = "c_10"
statusline_foreground = "c_83"
statusline_nc_background = "c_10"
statusline_nc_foreground = "c_49"
tabline_background = "c_10"
tabline_fill = "c_8"
tabline_foreground = "c_49"
tabline_sel_background = "c_74"
tabline_sel_foreground = "c_8"
warning = "c_92"
whitespace = "c_49"

[syntax]
boolean = "c_96"
character = "c_81"
comment = "c_29"
constant = "c_96"
constructor = "c_88"
delimiter = "c_29"
error = "c_91"
float = "c_96"
function = "c_74"
heading = "c_74"
keyword = "c_76"
link = "c_5"
module = "c_76"
number = "c_96"
operator = "c_77"
property = "c_73"
special = "c_29"
string = "c_81"
tag = "c_29"
tag_attribute = "c_73"
tag_delimiter = "c_29"
todo = "c_14"
type = "c_29"
variable = "c_89"
