[metadata]
name = "tokyonight-moon"
description = ""
author = "github/folke"
github = "https://github.com/folke/tokyonight.nvim"
type = "dark"

[colors]
c_0 = "#005523"
c_1 = "#0db9d7"
c_2 = "#119bb7"
c_3 = "#157d97"
c_4 = "#181a26"
c_5 = "#1a6076"
c_6 = "#1b1d2b"
c_7 = "#1c5166"
c_8 = "#1e2030"
c_9 = "#203346"
c_10 = "#222436"
c_11 = "#24283c"
c_12 = "#242d3d"
c_13 = "#252a3f"
c_14 = "#262f50"
c_15 = "#27293a"
c_16 = "#272a3f"
c_17 = "#272b40"
c_18 = "#273644"
c_19 = "#293047"
c_20 = "#29334a"
c_21 = "#2a2a40"
c_22 = "#2a2e3a"
c_23 = "#2a4556"
c_24 = "#2c3048"
c_25 = "#2c314a"
c_26 = "#2d283a"
c_27 = "#2d2a39"
c_28 = "#2d2b3f"
c_29 = "#2d2c39"
c_30 = "#2d3f76"
c_31 = "#2f334c"
c_32 = "#2f334d"
c_33 = "#322639"
c_34 = "#32304a"
c_35 = "#32383f"
c_36 = "#363a58"
c_37 = "#363c58"
c_38 = "#365272"
c_39 = "#382c3d"
c_40 = "#382f3b"
c_41 = "#383148"
c_42 = "#38343d"
c_43 = "#394b70"
c_44 = "#3b4261"
c_45 = "#3c4163"
c_46 = "#3e68d7"
c_47 = "#41a6b5"
c_48 = "#444a73"
c_49 = "#46b2a3"
c_50 = "#4b2a3d"
c_51 = "#4f5258"
c_52 = "#4fd6be"
c_53 = "#532b3f"
c_54 = "#545c7e"
c_55 = "#589ed7"
c_56 = "#590008"
c_57 = "#632d42"
c_58 = "#634b6c"
c_59 = "#63698c"
c_60 = "#636da6"
c_61 = "#64554a"
c_62 = "#6582c3"
c_63 = "#65bcff"
c_64 = "#6a88cc"
c_65 = "#6b5300"
c_66 = "#737aa2"
c_67 = "#79587e"
c_68 = "#7a6550"
c_69 = "#7ca1f2"
c_70 = "#828bb8"
c_71 = "#82aaff"
c_72 = "#83c3fc"
c_73 = "#86e1fc"
c_74 = "#89ddff"
c_75 = "#8cf8f7"
c_76 = "#9ab677"
c_77 = "#a4364d"
c_78 = "#b3f6c0"
c_79 = "#b4f9f8"
c_80 = "#b8db87"
c_81 = "#bc5c68"
c_82 = "#bd9664"
c_83 = "#c099ff"
c_84 = "#c3e88d"
c_85 = "#c53b53"
c_86 = "#c8d3f5"
c_87 = "#d3a66a"
c_88 = "#e26a75"
c_89 = "#f4c990"
c_90 = "#fca7ea"
c_91 = "#ff0000"
c_92 = "#ff007c"
c_93 = "#ff757f"
c_94 = "#ff966c"
c_95 = "#ffc0b9"
c_96 = "#ffc777"
c_97 = "#ffffff"

[ui]
background = "c_10"
border_background = "c_10"
border_foreground = "c_6"
caret = "c_10"
cursor_line = "c_32"
cursor_line_nr = "c_94"
diagnostic_error = "c_85"
diagnostic_hint = "c_52"
diagnostic_info = "c_1"
diagnostic_ok = "c_78"
diagnostic_warn = "c_96"
diff_add_background = "c_23"
diff_add_foreground = "c_78"
diff_change_background = "c_13"
diff_change_foreground = "c_75"
diff_delete_background = "c_50"
diff_delete_foreground = "c_95"
diff_text_background = "c_43"
error = "c_85"
find_highlight = "c_94"
find_highlight_foreground = "c_6"
float_background = "c_8"
float_border_background = "c_8"
float_border_foreground = "c_55"
float_foreground = "c_86"
foreground = "c_86"
gutter = "c_10"
gutter_foreground = "c_44"
match_paren_background = "c_10"
match_paren_foreground = "c_94"
non_text = "c_54"
pmenu_background = "c_8"
pmenu_foreground = "c_86"
pmenu_sbar = "c_15"
pmenu_sel_background = "c_37"
pmenu_sel_foreground = "c_86"
pmenu_thumb = "c_44"
selection = "c_30"
special_key = "c_54"
statusline_background = "c_8"
statusline_foreground = "c_70"
statusline_nc_background = "c_8"
statusline_nc_foreground = "c_44"
tabline_background = "c_8"
tabline_fill = "c_6"
tabline_foreground = "c_44"
tabline_sel_background = "c_71"
tabline_sel_foreground = "c_6"
warning = "c_96"
whitespace = "c_44"

[syntax]
boolean = "c_94"
character = "c_84"
comment = "c_63"
constant = "c_94"
constructor = "c_83"
delimiter = "c_63"
error = "c_85"
float = "c_94"
function = "c_71"
heading = "c_71"
keyword = "c_73"
link = "c_52"
module = "c_73"
number = "c_94"
operator = "c_74"
property = "c_52"
special = "c_63"
string = "c_84"
tag = "c_63"
tag_attribute = "c_52"
tag_delimiter = "c_63"
todo = "c_10"
type = "c_63"
variable = "c_86"
