[metadata]
name = "tokyonight-night"
description = ""
author = "github/folke"
github = "https://github.com/folke/tokyonight.nvim"
type = "dark"

[colors]
c_0 = "#005523"
c_1 = "#0db9d7"
c_2 = "#1099b4"
c_3 = "#121218"
c_4 = "#127a90"
c_5 = "#15161e"
c_6 = "#155a6d"
c_7 = "#16161e"
c_8 = "#164a5b"
c_9 = "#192b38"
c_10 = "#1a1b26"
c_11 = "#1a232c"
c_12 = "#1a2b32"
c_13 = "#1a9c84"
c_14 = "#1abc9c"
c_15 = "#1c2c38"
c_16 = "#1d202d"
c_17 = "#1f1f29"
c_18 = "#1f2230"
c_19 = "#1f2231"
c_20 = "#1f4d5d"
c_21 = "#202331"
c_22 = "#20253a"
c_23 = "#21202f"
c_24 = "#212429"
c_25 = "#222130"
c_26 = "#23293c"
c_27 = "#242229"
c_28 = "#24293b"
c_29 = "#243e4a"
c_30 = "#25202b"
c_31 = "#252229"
c_32 = "#262a3c"
c_33 = "#272538"
c_34 = "#272d2d"
c_35 = "#27a1b9"
c_36 = "#283457"
c_37 = "#292e42"
c_38 = "#2a283b"
c_39 = "#2ac3de"
c_40 = "#2b2f44"
c_41 = "#2c2f44"
c_42 = "#2d202a"
c_43 = "#2e2a2d"
c_44 = "#302430"
c_45 = "#31282c"
c_46 = "#32364e"
c_47 = "#343a55"
c_48 = "#394b70"
c_49 = "#3b4261"
c_50 = "#3c8390"
c_51 = "#3d59a1"
c_52 = "#41385b"
c_53 = "#414868"
c_54 = "#41a6b5"
c_55 = "#449dab"
c_56 = "#4a272f"
c_57 = "#4e426d"
c_58 = "#4f5258"
c_59 = "#536e9d"
c_60 = "#542931"
c_61 = "#545c7e"
c_62 = "#55473a"
c_63 = "#565f89"
c_64 = "#57c5e5"
c_65 = "#590008"
c_66 = "#5d7ab8"
c_67 = "#616789"
c_68 = "#6183bb"
c_69 = "#672e35"
c_70 = "#695640"
c_71 = "#6b5300"
c_72 = "#737aa2"
c_73 = "#73daca"
c_74 = "#79424b"
c_75 = "#7aa2f7"
c_76 = "#7dcfff"
c_77 = "#89ddff"
c_78 = "#8cf8f7"
c_79 = "#914c54"
c_80 = "#9d7cd8"
c_81 = "#9ece6a"
c_82 = "#a58354"
c_83 = "#a9b1d6"
c_84 = "#b3f6c0"
c_85 = "#b44144"
c_86 = "#b4f9f8"
c_87 = "#b8915b"
c_88 = "#bb9af7"
c_89 = "#c0caf5"
c_90 = "#dab484"
c_91 = "#db4b4b"
c_92 = "#e0af68"
c_93 = "#f7768e"
c_94 = "#ff0000"
c_95 = "#ff007c"
c_96 = "#ff9e64"
c_97 = "#ffc0b9"
c_98 = "#ffffff"

[ui]
background = "c_10"
border_background = "c_10"
border_foreground = "c_5"
caret = "c_10"
cursor_line = "c_37"
cursor_line_nr = "c_96"
diagnostic_error = "c_91"
diagnostic_hint = "c_14"
diagnostic_info = "c_1"
diagnostic_ok = "c_84"
diagnostic_warn = "c_92"
diff_add_background = "c_29"
diff_add_foreground = "c_84"
diff_change_background = "c_19"
diff_change_foreground = "c_78"
diff_delete_background = "c_56"
diff_delete_foreground = "c_97"
diff_text_background = "c_48"
error = "c_91"
find_highlight = "c_96"
find_highlight_foreground = "c_5"
float_background = "c_7"
float_border_background = "c_7"
float_border_foreground = "c_35"
float_foreground = "c_89"
foreground = "c_89"
gutter = "c_10"
gutter_foreground = "c_49"
match_paren_background = "c_10"
match_paren_foreground = "c_96"
non_text = "c_61"
pmenu_background = "c_7"
pmenu_foreground = "c_89"
pmenu_sbar = "c_17"
pmenu_sel_background = "c_47"
pmenu_sel_foreground = "c_89"
pmenu_thumb = "c_49"
selection = "c_36"
special_key = "c_61"
statusline_background = "c_7"
statusline_foreground = "c_83"
statusline_nc_background = "c_7"
statusline_nc_foreground = "c_49"
tabline_background = "c_7"
tabline_fill = "c_5"
tabline_foreground = "c_49"
tabline_sel_background = "c_75"
tabline_sel_foreground = "c_5"
warning = "c_92"
whitespace = "c_49"

[syntax]
boolean = "c_96"
character = "c_81"
comment = "c_63"
constant = "c_96"
constructor = "c_88"
delimiter = "c_39"
error = "c_91"
float = "c_96"
function = "c_75"
heading = "c_75"
keyword = "c_76"
link = "c_14"
module = "c_76"
number = "c_96"
operator = "c_77"
property = "c_73"
special = "c_96"
string = "c_81"
tag = "c_88"
tag_attribute = "c_73"
tag_delimiter = "c_39"
todo = "c_10"
type = "c_39"
variable = "c_89"
