[metadata]
name = "tokyonight-day"
description = ""
author = "github/folke"
github = "https://github.com/folke/tokyonight.nvim"
type = "light"

[colors]
c_0 = "#005523"
c_1 = "#006a83"
c_2 = "#007197"
c_3 = "#007373"
c_4 = "#07879d"
c_5 = "#118c74"
c_6 = "#188092"
c_7 = "#2176a0"
c_8 = "#2e5857"
c_9 = "#2e7de9"
c_10 = "#3399ac"
c_11 = "#3760bf"
c_12 = "#387068"
c_13 = "#38919f"
c_14 = "#3b9d8b"
c_15 = "#4094a3"
c_16 = "#4197a4"
c_17 = "#506d9c"
c_18 = "#587539"
c_19 = "#590008"
c_20 = "#5eabbb"
c_21 = "#6172b0"
c_22 = "#61a6b1"
c_23 = "#649be8"
c_24 = "#68709a"
c_25 = "#6d84ab"
c_26 = "#7847bd"
c_27 = "#7890dd"
c_28 = "#7b6a58"
c_29 = "#8087a9"
c_30 = "#848cb5"
c_31 = "#8990b3"
c_32 = "#8abec9"
c_33 = "#8c6c3e"
c_34 = "#92a6d5"
c_35 = "#9854f1"
c_36 = "#9b9ea4"
c_37 = "#9d8460"
c_38 = "#a0c7d1"
c_39 = "#a1a6c5"
c_40 = "#a5c5ce"
c_41 = "#a68f71"
c_42 = "#a8aecb"
c_43 = "#b0c3e4"
c_44 = "#b15c00"
c_45 = "#b3b8d1"
c_46 = "#b3f6c0"
c_47 = "#b4b5b9"
c_48 = "#b7a4d6"
c_49 = "#b7c1e3"
c_50 = "#b7ced5"
c_51 = "#bcc0d3"
c_52 = "#bfb3a3"
c_53 = "#c2b4da"
c_54 = "#c47981"
c_55 = "#c4c8da"
c_56 = "#c5c8d8"
c_57 = "#c5c8d9"
c_58 = "#c64343"
c_59 = "#c8bfb4"
c_60 = "#c8cfe1"
c_61 = "#c9d0e2"
c_62 = "#ca8e95"
c_63 = "#cacddd"
c_64 = "#cb6364"
c_65 = "#cbd9e0"
c_66 = "#ccd9dc"
c_67 = "#cdd8df"
c_68 = "#cfd8e7"
c_69 = "#d0d5e3"
c_70 = "#d0d5e5"
c_71 = "#d20065"
c_72 = "#d3d7d6"
c_73 = "#d5d8e2"
c_74 = "#d5d9e4"
c_75 = "#d6a2a5"
c_76 = "#d7d3e3"
c_77 = "#d7dee1"
c_78 = "#d8dde7"
c_79 = "#d9b2b6"
c_80 = "#d9d6d6"
c_81 = "#d9dce5"
c_82 = "#dababe"
c_83 = "#dad4e8"
c_84 = "#daddde"
c_85 = "#dcd5d0"
c_86 = "#dcdae5"
c_87 = "#dddbe8"
c_88 = "#dddcdf"
c_89 = "#ded2d7"
c_90 = "#dfdbdb"
c_91 = "#e1e2e7"
c_92 = "#e2d9e1"
c_93 = "#e3d0da"
c_94 = "#f52a65"
c_95 = "#fce094"
c_96 = "#ff0000"
c_97 = "#ffc0b9"
c_98 = "#ffffff"

[ui]
background = "c_91"
border_background = "c_91"
border_foreground = "c_47"
caret = "c_91"
cursor_line = "c_55"
cursor_line_nr = "c_44"
diagnostic_error = "c_58"
diagnostic_hint = "c_5"
diagnostic_info = "c_4"
diagnostic_ok = "c_0"
diagnostic_warn = "c_33"
diff_add_background = "c_50"
diff_add_foreground = "c_0"
diff_change_background = "c_74"
diff_change_foreground = "c_3"
diff_delete_background = "c_82"
diff_delete_foreground = "c_19"
diff_text_background = "c_34"
error = "c_58"
find_highlight = "c_27"
find_highlight_foreground = "c_11"
float_background = "c_69"
float_border_background = "c_69"
float_border_foreground = "c_15"
float_foreground = "c_11"
foreground = "c_11"
gutter = "c_91"
gutter_foreground = "c_42"
match_paren_background = "c_91"
match_paren_foreground = "c_44"
non_text = "c_31"
pmenu_background = "c_69"
pmenu_foreground = "c_11"
pmenu_sbar = "c_60"
pmenu_sel_background = "c_45"
pmenu_sel_foreground = "c_11"
pmenu_thumb = "c_42"
selection = "c_49"
special_key = "c_31"
statusline_background = "c_69"
statusline_foreground = "c_21"
statusline_nc_background = "c_69"
statusline_nc_foreground = "c_42"
tabline_background = "c_69"
tabline_fill = "c_47"
tabline_foreground = "c_42"
tabline_sel_background = "c_9"
tabline_sel_foreground = "c_47"
warning = "c_33"
whitespace = "c_42"

[syntax]
boolean = "c_44"
character = "c_18"
comment = "c_30"
constant = "c_44"
constructor = "c_35"
delimiter = "c_6"
error = "c_58"
float = "c_44"
function = "c_9"
heading = "c_9"
keyword = "c_2"
link = "c_5"
module = "c_2"
number = "c_44"
operator = "c_1"
property = "c_12"
special = "c_6"
string = "c_18"
tag = "c_6"
tag_attribute = "c_12"
tag_delimiter = "c_6"
todo = "c_91"
type = "c_6"
variable = "c_11"
